vara-feature: vara::feature::Constraint Class Reference
vara::feature::Constraint Class Reference abstract
Tree like representation of constraints between features.
#include "vara/Feature/Constraint.h"
Public Types
enum ConstraintKind {
ConstraintKind::CK_ADDITION, ConstraintKind::CK_AND, ConstraintKind::CK_BINARY, ConstraintKind::CK_DIVISION,
ConstraintKind::CK_EQUAL, ConstraintKind::CK_EQUIVALENCE, ConstraintKind::CK_EXCLUDES, ConstraintKind::CK_FEATURE,
ConstraintKind::CK_GREATER, ConstraintKind::CK_GREATER_EQUAL, ConstraintKind::CK_IMPLIES, ConstraintKind::CK_INTEGER,
ConstraintKind::CK_LESS, ConstraintKind::CK_LESS_EQUAL, ConstraintKind::CK_MULTIPLICATION, ConstraintKind::CK_NEG,
ConstraintKind::CK_NOT, ConstraintKind::CK_NOT_EQUAL, ConstraintKind::CK_OR, ConstraintKind::CK_PRIMARY,
ConstraintKind::CK_SUBTRACTION, ConstraintKind::CK_UNARY, ConstraintKind::CK_XOR
}
Public Member Functions
Constraint (ConstraintKind Kind)
Constraint (const Constraint &)=delete
Constraint & operator= (Constraint &)=delete
Constraint (Constraint &&)=delete
Constraint & operator= (Constraint &&)=delete
virtual ~Constraint ()=default
ConstraintKind getKind () const
void setParent (Constraint *P)
Constraint * getParent ()
Constraint * getRoot ()
virtual std::unique_ptr< Constraint > clone ()=0
Recursively clones constraint tree.
virtual std::string toString () const =0
virtual std::string toHTML () const
virtual void accept (ConstraintVisitor &V)=0
Detailed Description
Tree like representation of constraints between features.
Definition at line 23 of file Constraint.h.
Member Enumeration Documentation
ConstraintKind
enum vara::feature::Constraint::ConstraintKind strong
Enumerator
CK_ADDITION
CK_AND
CK_BINARY
CK_DIVISION
CK_EQUAL
CK_EQUIVALENCE
CK_EXCLUDES
CK_FEATURE
CK_GREATER
CK_GREATER_EQUAL
CK_IMPLIES
CK_INTEGER
CK_LESS
CK_LESS_EQUAL
CK_MULTIPLICATION
CK_NEG
CK_NOT
CK_NOT_EQUAL
CK_OR
CK_PRIMARY
CK_SUBTRACTION
CK_UNARY
CK_XOR
Definition at line 25 of file Constraint.h.
Constructor & Destructor Documentation
Constraint() [1/3]
vara::feature::Constraint::Constraint (ConstraintKind Kind) inline
Definition at line 51 of file Constraint.h.
Constraint() [2/3]
vara::feature::Constraint::Constraint (const Constraint &) delete
Constraint() [3/3]
vara::feature::Constraint::Constraint (Constraint &&) delete
~Constraint()
virtual vara::feature::Constraint::~Constraint () virtual default
Member Function Documentation
accept()
virtual void vara::feature::Constraint::accept (ConstraintVisitor & V) pure virtual
Implemented in vara::feature::PrimaryFeatureConstraint, vara::feature::PrimaryIntegerConstraint, vara::feature::UnaryConstraint, and vara::feature::BinaryConstraint.
Referenced by vara::feature::ConstraintVisitor::visit().
clone()
virtual std::unique_ptr<Constraint> vara::feature::Constraint::clone () pure virtual
Recursively clones constraint tree.
If this tree contains special nodes (like PrimaryFeatureConstraint) those may need to be updated afterwards.
Returns
root of cloned constraint tree
Implemented in vara::feature::PrimaryFeatureConstraint, vara::feature::PrimaryIntegerConstraint, vara::feature::NegConstraint, vara::feature::NotConstraint, vara::feature::GreaterEqualConstraint, vara::feature::LessEqualConstraint, vara::feature::GreaterConstraint, vara::feature::LessConstraint, vara::feature::DivisionConstraint, vara::feature::MultiplicationConstraint, vara::feature::SubtractionConstraint, vara::feature::AdditionConstraint, vara::feature::EquivalenceConstraint, vara::feature::ExcludesConstraint, vara::feature::ImpliesConstraint, vara::feature::NotEqualConstraint, vara::feature::EqualConstraint, vara::feature::AndConstraint, vara::feature::XorConstraint, and vara::feature::OrConstraint.
getKind()
ConstraintKind vara::feature::Constraint::getKind () const inline
Definition at line 58 of file Constraint.h.
Referenced by vara::feature::OrConstraint::classof(), vara::feature::XorConstraint::classof(), vara::feature::AndConstraint::classof(), vara::feature::EqualConstraint::classof(), vara::feature::NotEqualConstraint::classof(), vara::feature::ImpliesConstraint::classof(), vara::feature::ExcludesConstraint::classof(), vara::feature::EquivalenceConstraint::classof(), vara::feature::AdditionConstraint::classof(), vara::feature::SubtractionConstraint::classof(), vara::feature::MultiplicationConstraint::classof(), vara::feature::DivisionConstraint::classof(), vara::feature::LessConstraint::classof(), vara::feature::GreaterConstraint::classof(), vara::feature::LessEqualConstraint::classof(), vara::feature::GreaterEqualConstraint::classof(), vara::feature::NotConstraint::classof(), vara::feature::NegConstraint::classof(), vara::feature::PrimaryIntegerConstraint::classof(), and vara::feature::PrimaryFeatureConstraint::classof().
getParent()
Constraint* vara::feature::Constraint::getParent () inline
Definition at line 62 of file Constraint.h.
getRoot()
Constraint* vara::feature::Constraint::getRoot () inline
Definition at line 64 of file Constraint.h.
operator=() [1/2]
Constraint& vara::feature::Constraint::operator= (Constraint &&) delete
operator=() [2/2]
Constraint& vara::feature::Constraint::operator= (Constraint &) delete
setParent()
void vara::feature::Constraint::setParent (Constraint * P) inline
Definition at line 60 of file Constraint.h.
toHTML()
virtual std::string vara::feature::Constraint::toHTML () const inline virtual
Reimplemented in vara::feature::GreaterEqualConstraint, vara::feature::LessEqualConstraint, vara::feature::GreaterConstraint, vara::feature::LessConstraint, vara::feature::EquivalenceConstraint, vara::feature::ExcludesConstraint, vara::feature::ImpliesConstraint, and vara::feature::AndConstraint.
Definition at line 81 of file Constraint.h.
References toString().
toString()
virtual std::string vara::feature::Constraint::toString () const pure virtual
Implemented in vara::feature::PrimaryFeatureConstraint, vara::feature::PrimaryIntegerConstraint, vara::feature::NegConstraint, vara::feature::NotConstraint, vara::feature::GreaterEqualConstraint, vara::feature::LessEqualConstraint, vara::feature::GreaterConstraint, vara::feature::LessConstraint, vara::feature::DivisionConstraint, vara::feature::MultiplicationConstraint, vara::feature::SubtractionConstraint, vara::feature::AdditionConstraint, vara::feature::EquivalenceConstraint, vara::feature::ExcludesConstraint, vara::feature::ImpliesConstraint, vara::feature::NotEqualConstraint, vara::feature::EqualConstraint, vara::feature::AndConstraint, vara::feature::XorConstraint, and vara::feature::OrConstraint.
Referenced by toHTML().
The documentation for this class was generated from the following file:
include/vara/Feature/Constraint.h