vara-feature: vara::feature::UnaryConstraint Class Reference
vara::feature::UnaryConstraint Class Reference
#include "vara/Feature/Constraint.h"
Public Member Functions
UnaryConstraint (ConstraintKind Kind, std::unique_ptr< Constraint > Operand)
Constraint * getOperand ()
void accept (ConstraintVisitor &V) override
Public Member Functions inherited from vara::feature::Constraint
Constraint (ConstraintKind Kind)
Constraint (const Constraint &)=delete
Constraint & operator= (Constraint &)=delete
Constraint (Constraint &&)=delete
Constraint & operator= (Constraint &&)=delete
virtual ~Constraint ()=default
ConstraintKind getKind () const
void setParent (Constraint *P)
Constraint * getParent ()
Constraint * getRoot ()
virtual std::unique_ptr< Constraint > clone ()=0
Recursively clones constraint tree.
virtual std::string toString () const =0
virtual std::string toHTML () const
Protected Attributes
std::unique_ptr< Constraint > Operand
Additional Inherited Members
Public Types inherited from vara::feature::Constraint
enum ConstraintKind {
ConstraintKind::CK_ADDITION, ConstraintKind::CK_AND, ConstraintKind::CK_BINARY, ConstraintKind::CK_DIVISION,
ConstraintKind::CK_EQUAL, ConstraintKind::CK_EQUIVALENCE, ConstraintKind::CK_EXCLUDES, ConstraintKind::CK_FEATURE,
ConstraintKind::CK_GREATER, ConstraintKind::CK_GREATER_EQUAL, ConstraintKind::CK_IMPLIES, ConstraintKind::CK_INTEGER,
ConstraintKind::CK_LESS, ConstraintKind::CK_LESS_EQUAL, ConstraintKind::CK_MULTIPLICATION, ConstraintKind::CK_NEG,
ConstraintKind::CK_NOT, ConstraintKind::CK_NOT_EQUAL, ConstraintKind::CK_OR, ConstraintKind::CK_PRIMARY,
ConstraintKind::CK_SUBTRACTION, ConstraintKind::CK_UNARY, ConstraintKind::CK_XOR
}
Detailed Description
Definition at line 513 of file Constraint.h.
Constructor & Destructor Documentation
UnaryConstraint()
vara::feature::UnaryConstraint::UnaryConstraint (ConstraintKind Kind, std::unique_ptr< Constraint > Operand) inline
Definition at line 515 of file Constraint.h.
Member Function Documentation
accept()
void vara::feature::UnaryConstraint::accept (ConstraintVisitor & V) override virtual
Implements vara::feature::Constraint.
Definition at line 7 of file Constraint.cpp.
References vara::feature::ConstraintVisitor::visit().
getOperand()
Constraint* vara::feature::UnaryConstraint::getOperand () inline
Definition at line 520 of file Constraint.h.
References Operand.
Referenced by vara::feature::NotConstraint::clone(), vara::feature::NegConstraint::clone(), and vara::feature::ConstraintVisitor::visit().
Member Data Documentation
Operand
std::unique_ptr<Constraint> vara::feature::UnaryConstraint::Operand protected
Definition at line 525 of file Constraint.h.
Referenced by getOperand(), vara::feature::NotConstraint::toString(), and vara::feature::NegConstraint::toString().
The documentation for this class was generated from the following files:
include/vara/Feature/Constraint.h
lib/Feature/Constraint.cpp