vara-feature: vara::feature::PrimaryIntegerConstraint Class Reference
vara::feature::PrimaryIntegerConstraint Class Reference
#include "vara/Feature/Constraint.h"
Public Member Functions
PrimaryIntegerConstraint (int Value)
int getValue () const
std::unique_ptr< Constraint > clone () override
Recursively clones constraint tree.
std::string toString () const override
void accept (ConstraintVisitor &V) override
Public Member Functions inherited from vara::feature::PrimaryConstraint
PrimaryConstraint (ConstraintKind Kind)
Public Member Functions inherited from vara::feature::Constraint
Constraint (ConstraintKind Kind)
Constraint (const Constraint &)=delete
Constraint & operator= (Constraint &)=delete
Constraint (Constraint &&)=delete
Constraint & operator= (Constraint &&)=delete
virtual ~Constraint ()=default
ConstraintKind getKind () const
void setParent (Constraint *P)
Constraint * getParent ()
Constraint * getRoot ()
virtual std::string toHTML () const
Static Public Member Functions
static bool classof (const Constraint *C)
Additional Inherited Members
Public Types inherited from vara::feature::Constraint
enum ConstraintKind {
ConstraintKind::CK_ADDITION, ConstraintKind::CK_AND, ConstraintKind::CK_BINARY, ConstraintKind::CK_DIVISION,
ConstraintKind::CK_EQUAL, ConstraintKind::CK_EQUIVALENCE, ConstraintKind::CK_EXCLUDES, ConstraintKind::CK_FEATURE,
ConstraintKind::CK_GREATER, ConstraintKind::CK_GREATER_EQUAL, ConstraintKind::CK_IMPLIES, ConstraintKind::CK_INTEGER,
ConstraintKind::CK_LESS, ConstraintKind::CK_LESS_EQUAL, ConstraintKind::CK_MULTIPLICATION, ConstraintKind::CK_NEG,
ConstraintKind::CK_NOT, ConstraintKind::CK_NOT_EQUAL, ConstraintKind::CK_OR, ConstraintKind::CK_PRIMARY,
ConstraintKind::CK_SUBTRACTION, ConstraintKind::CK_UNARY, ConstraintKind::CK_XOR
}
Detailed Description
Definition at line 571 of file Constraint.h.
Constructor & Destructor Documentation
PrimaryIntegerConstraint()
vara::feature::PrimaryIntegerConstraint::PrimaryIntegerConstraint (int Value) inline
Definition at line 573 of file Constraint.h.
Member Function Documentation
accept()
void vara::feature::PrimaryIntegerConstraint::accept (ConstraintVisitor & V) override virtual
Implements vara::feature::Constraint.
Definition at line 9 of file Constraint.cpp.
References vara::feature::ConstraintVisitor::visit().
classof()
static bool vara::feature::PrimaryIntegerConstraint::classof (const Constraint * C) inline static
Definition at line 586 of file Constraint.h.
References vara::feature::Constraint::CK_INTEGER, and vara::feature::Constraint::getKind().
clone()
std::unique_ptr<Constraint> vara::feature::PrimaryIntegerConstraint::clone () inline override virtual
Recursively clones constraint tree.
If this tree contains special nodes (like PrimaryFeatureConstraint) those may need to be updated afterwards.
Returns
root of cloned constraint tree
Implements vara::feature::Constraint.
Definition at line 578 of file Constraint.h.
References getValue().
getValue()
int vara::feature::PrimaryIntegerConstraint::getValue () const inline
Definition at line 576 of file Constraint.h.
Referenced by clone().
toString()
std::string vara::feature::PrimaryIntegerConstraint::toString () const inline override virtual
Implements vara::feature::Constraint.
Definition at line 582 of file Constraint.h.
The documentation for this class was generated from the following files:
include/vara/Feature/Constraint.h
lib/Feature/Constraint.cpp