vara-feature: vara::solver::SolverFactory Class Reference
vara::solver::SolverFactory Class Reference
This class constructs a solver instance that optionally initializes the solver using a certain feature model.
#include "vara/Solver/SolverFactory.h"
Static Public Member Functions
static std::unique_ptr< Solver > initializeSolver (const feature::FeatureModel &Model, const SolverType Type)
This method returns a pointer to an initialized solver.
static std::unique_ptr< Solver > initializeSolver (const SolverType Type)
This method returns a pointer to an initialized solver.
Detailed Description
This class constructs a solver instance that optionally initializes the solver using a certain feature model.
Definition at line 15 of file SolverFactory.h.
Member Function Documentation
initializeSolver() [1/2]
static std::unique_ptr<Solver> vara::solver::SolverFactory::initializeSolver (const feature::FeatureModel & Model, const SolverType Type) inline static
This method returns a pointer to an initialized solver.
This solver has already processed the features and constraints of the given feature model.
Parameters
Model the model to use for the initialization of the solver
Type the type of solver to use
Returns
a unique pointer containing the initialized solver
Definition at line 25 of file SolverFactory.h.
References vara::solver::Z3.
Referenced by vara::solver::ConfigurationFactory::getAllConfigs(), vara::solver::ConfigurationFactory::getConfigIterator(), initializeSolver(), and vara::solver::ConfigurationFactory::isValid().
initializeSolver() [2/2]
static std::unique_ptr<Solver> vara::solver::SolverFactory::initializeSolver (const SolverType Type) inline static
This method returns a pointer to an initialized solver.
Parameters
Type the type of solver to use
Returns
a unique pointer containing the initialized solver
Definition at line 40 of file SolverFactory.h.
References vara::feature::FeatureModelBuilder::buildFeatureModel(), and initializeSolver().
The documentation for this class was generated from the following files:
include/vara/Solver/SolverFactory.h
lib/Solver/SolverFactory.cpp