vara-feature: vara::Result< ErrorTy, ValueTy > Class Template Reference
vara::Result< ErrorTy, ValueTy > Class Template Reference
#include "vara/Utils/Result.h"
Public Member Functions
Result (Ok< ValueTy > V)
Result (Error< ErrorTy > E)
template<typename... ArgsTy, std::enable_if_t< std::is_constructible_v< ValueTy, ArgsTy... >, bool > = true>
Result (ArgsTy &&...Args)
template<typename... ArgsTy, std::enable_if_t< std::is_constructible_v< ErrorTy, ArgsTy... >, bool > = true>
Result (ArgsTy &&...Args)
operator bool () const
Return false if there is an error.
ValueTy operator* () &
ValueTy operator* () &&
ValueTy extractValue ()
ErrorTy getError () &
ErrorTy getError () &&
ErrorTy extractError ()
Protected Attributes
std::variant< Ok< ValueTy >, Error< ErrorTy > > Variant
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Result< ErrorTy, ValueTy > &R)
Detailed Description
template<typename ErrorTy, typename ValueTy = void>
class vara::Result< ErrorTy, ValueTy >
Definition at line 92 of file Result.h.
Constructor & Destructor Documentation
Result() [1/4]
template<typename ErrorTy , typename ValueTy = void> vara::Result< ErrorTy, ValueTy >::Result (Ok< ValueTy > V) inline
Definition at line 94 of file Result.h.
Result() [2/4]
template<typename ErrorTy , typename ValueTy = void> vara::Result< ErrorTy, ValueTy >::Result (Error< ErrorTy > E) inline
Definition at line 96 of file Result.h.
Result() [3/4]
template<typename ErrorTy , typename ValueTy = void> template<typename... ArgsTy, std::enable_if_t< std::is_constructible_v< ValueTy, ArgsTy... >, bool > = true> vara::Result< ErrorTy, ValueTy >::Result (ArgsTy &&... Args) inline
Definition at line 101 of file Result.h.
Result() [4/4]
template<typename ErrorTy , typename ValueTy = void> template<typename... ArgsTy, std::enable_if_t< std::is_constructible_v< ErrorTy, ArgsTy... >, bool > = true> vara::Result< ErrorTy, ValueTy >::Result (ArgsTy &&... Args) inline
Definition at line 108 of file Result.h.
Member Function Documentation
extractError()
template<typename ErrorTy , typename ValueTy = void> ErrorTy vara::Result< ErrorTy, ValueTy >::extractError () inline
Definition at line 136 of file Result.h.
References vara::Result< ErrorTy, ValueTy >::Variant.
Referenced by vara::Result< ErrorTy, ValueTy >::getError().
extractValue()
template<typename ErrorTy , typename ValueTy = void> ValueTy vara::Result< ErrorTy, ValueTy >::extractValue () inline
Definition at line 124 of file Result.h.
References vara::Result< ErrorTy, ValueTy >::Variant.
Referenced by vara::Result< ErrorTy, ValueTy >::operator*().
getError() [1/2]
template<typename ErrorTy , typename ValueTy = void> ErrorTy vara::Result< ErrorTy, ValueTy >::getError () & inline
Definition at line 129 of file Result.h.
References vara::Result< ErrorTy, ValueTy >::Variant.
getError() [2/2]
template<typename ErrorTy , typename ValueTy = void> ErrorTy vara::Result< ErrorTy, ValueTy >::getError () && inline
Definition at line 134 of file Result.h.
References vara::Result< ErrorTy, ValueTy >::extractError().
operator bool()
template<typename ErrorTy , typename ValueTy = void> vara::Result< ErrorTy, ValueTy >::operator bool () const inline
Return false if there is an error.
Definition at line 113 of file Result.h.
References vara::Result< ErrorTy, ValueTy >::Variant.
operator*() [1/2]
template<typename ErrorTy , typename ValueTy = void> ValueTy vara::Result< ErrorTy, ValueTy >::operator* () & inline
Definition at line 117 of file Result.h.
References vara::Result< ErrorTy, ValueTy >::Variant.
operator*() [2/2]
template<typename ErrorTy , typename ValueTy = void> ValueTy vara::Result< ErrorTy, ValueTy >::operator* () && inline
Definition at line 122 of file Result.h.
References vara::Result< ErrorTy, ValueTy >::extractValue().
Friends And Related Function Documentation
operator<<
template<typename ErrorTy , typename ValueTy = void> llvm::raw_ostream& operator<< (llvm::raw_ostream & OS, const Result< ErrorTy, ValueTy > & R) friend
Definition at line 141 of file Result.h.
Member Data Documentation
Variant
template<typename ErrorTy , typename ValueTy = void> std::variant<Ok<ValueTy>, Error<ErrorTy> > vara::Result< ErrorTy, ValueTy >::Variant protected
Definition at line 148 of file Result.h.
Referenced by vara::Result< ErrorTy, ValueTy >::extractError(), vara::Result< ErrorTy, ValueTy >::extractValue(), vara::Result< ErrorTy, ValueTy >::getError(), vara::Result< ErrorTy, ValueTy >::operator bool(), and vara::Result< ErrorTy, ValueTy >::operator*().
The documentation for this class was generated from the following file:
include/vara/Utils/Result.h