vara-feature: vara::solver::Z3Solver Class Reference
vara::solver::Z3Solver Class Reference
The Z3 solver implementation for handling constraints.
#include "vara/Solver/Z3Solver.h"
Public Member Functions
Z3Solver (z3::config &Cfg)
Result< SolverErrorCode > addFeature (const feature::Feature &FeatureToAdd, bool IsInAlternativeGroup=false) override
Adds the given feature to the solver.
Result< SolverErrorCode > addFeature (const string &FeatureName) override
This method adds a boolean feature with the given name.
Result< SolverErrorCode > addFeature (const string &FeatureName, const std::vector< int64_t > &Values) override
Adds a numeric feature with the given name and the given values.
Result< SolverErrorCode > removeFeature (feature::Feature &FeatureToRemove) override
This method removes the given feature and all its constraints the feature is included in.
Result< SolverErrorCode > addRelationship (const feature::Relationship &R) override
Processes the given relationship.
Result< SolverErrorCode > addConstraint (feature::Constraint &ConstraintToAdd) override
Adds the given constraint to the solver.
Result< SolverErrorCode > addMixedConstraint (feature::Constraint &ConstraintToAdd, feature::FeatureModel::MixedConstraint::ExprKind ExprKind, feature::FeatureModel::MixedConstraint::Req Req) override
Adds the given mixedconstraint to the solver.
Result< SolverErrorCode, bool > hasValidConfigurations () override
Returns true if the current constraint system (i.e., its features and its constraints) has valid configurations.
Result< SolverErrorCode, std::unique_ptr< vara::feature::Configuration > > getCurrentConfiguration () override
Returns the current configuration.
Result< SolverErrorCode, uint64_t > getNumberValidConfigurations () override
Returns the number of valid configurations of the current constraint system (i.e., its features and its constraints).
Result< SolverErrorCode, std::unique_ptr< vara::feature::Configuration > > getNextConfiguration () override
This method returns the next configuration or an error in case of an error.
Result< SolverErrorCode, std::vector< std::unique_ptr< vara::feature::Configuration > > > getAllValidConfigurations () override
Returns all valid configurations.
Public Member Functions inherited from vara::solver::Solver
Solver ()=default
virtual ~Solver ()=default
Static Public Member Functions
static std::unique_ptr< Z3Solver > create ()
Friends
class Z3SolverConstraintVisitor
Detailed Description
The Z3 solver implementation for handling constraints.
Definition at line 20 of file Z3Solver.h.
Constructor & Destructor Documentation
Z3Solver()
vara::solver::Z3Solver::Z3Solver (z3::config & Cfg) inline explicit
Definition at line 22 of file Z3Solver.h.
Member Function Documentation
addConstraint()
Result< SolverErrorCode > vara::solver::Z3Solver::addConstraint (feature::Constraint & ConstraintToAdd) override virtual
Adds the given constraint to the solver.
In the case that the constraint includes features that were not included yet, a error is returned. So, make sure that all features are already added.
Parameters
ConstraintToAdd the constraint that should be added.
Returns
a possible error if adding the constraint could not be done.
Implements vara::solver::Solver.
Definition at line 147 of file Z3Solver.cpp.
References vara::solver::Z3SolverConstraintVisitor::addConstraint(), and vara::solver::NOT_SUPPORTED.
addFeature() [1/3]
Result< SolverErrorCode > vara::solver::Z3Solver::addFeature (const feature::Feature & FeatureToAdd, bool IsInAlternativeGroup = false) override virtual
Adds the given feature to the solver.
That is, a new variable is created in the solver and all its constraints are included. The second argument indicates whether the 'optional' constraint should be considered or not – note that this is needed since alternative features are modelled as not optional, but are neither optional nor mandatory.
Parameters
FeatureToAdd the feature that should be added.
IsInAlternativeGroup whether the feature is in an alternative group or not.
Returns
a possible error if adding the feature was not successful.
Implements vara::solver::Solver.
Definition at line 10 of file Z3Solver.cpp.
References addFeature(), vara::solver::ALREADY_PRESENT, vara::feature::Feature::FK_BINARY, vara::feature::Feature::FK_NUMERIC, vara::feature::Feature::FK_ROOT, vara::feature::Feature::FK_UNKNOWN, vara::feature::Feature::getKind(), vara::feature::Feature::getName(), vara::feature::Feature::getParentFeature(), vara::solver::NOT_SUPPORTED, and vara::solver::PARENT_NOT_PRESENT.
Referenced by addFeature().
addFeature() [2/3]
Result< SolverErrorCode > vara::solver::Z3Solver::addFeature (const string & FeatureName) override virtual
This method adds a boolean feature with the given name.
Please be aware that this method does only include a boolean feature with no constraints. If this is not intended, use the other methods, instead.
Parameters
FeatureName the name of the boolean feature to add
Returns
a possible error if adding the boolean feature was not successful.
Implements vara::solver::Solver.
Definition at line 87 of file Z3Solver.cpp.
References vara::solver::ALREADY_PRESENT.
addFeature() [3/3]
Result< SolverErrorCode > vara::solver::Z3Solver::addFeature (const string & FeatureName, const std::vector< int64_t > & Values) override virtual
Adds a numeric feature with the given name and the given values.
Be aware that this method includes a numeric feature with no constraints and the specified values. That is also the case if the values of the feature are 0 and 1. If this is not intended, use the other methods, instead.
Parameters
FeatureName the name of the numeric feature to add.
Values the values that the numeric feature can have.
Returns
a possible error if adding the numeric feature was not successful.
Implements vara::solver::Solver.
Definition at line 99 of file Z3Solver.cpp.
References vara::solver::ALREADY_PRESENT.
addMixedConstraint()
Result< SolverErrorCode > vara::solver::Z3Solver::addMixedConstraint (feature::Constraint & ConstraintToAdd, feature::FeatureModel::MixedConstraint::ExprKind ExprKind, feature::FeatureModel::MixedConstraint::Req Req) override virtual
Adds the given mixedconstraint to the solver.
In the case that the constraint includes features that were not included yet, a error is returned. So, make sure that all features are already added. Note that the difference to a normal constraint is that
Parameters
ConstraintToAdd the mixed constraint to add.
ExprKind the kind of expression: whether the constraint should be negated (neg) or not (pos).
Req whether the constraint evaluates to false (all) if not all boolean features are selected or not (none).
Returns
a possible error if adding the constraint could not be done.
Implements vara::solver::Solver.
Definition at line 156 of file Z3Solver.cpp.
References vara::solver::Z3SolverConstraintVisitor::addConstraint(), vara::feature::FeatureModel::MixedConstraint::ALL, vara::feature::FeatureModel::MixedConstraint::NEG, and vara::solver::NOT_SUPPORTED.
addRelationship()
Result< SolverErrorCode > vara::solver::Z3Solver::addRelationship (const feature::Relationship & R) override virtual
Processes the given relationship.
This can be either an ALTERNATIVE group or an OR group.
Parameters
R the relationship to add.
Returns
a possible error if adding the relationship could not be done.
Implements vara::solver::Solver.
Definition at line 125 of file Z3Solver.cpp.
References vara::feature::FeatureTreeNode::children(), vara::feature::Relationship::getKind(), vara::feature::FeatureTreeNode::getParent(), vara::feature::Relationship::RK_ALTERNATIVE, and vara::feature::Relationship::RK_OR.
create()
static std::unique_ptr<Z3Solver> vara::solver::Z3Solver::create () inline static
Definition at line 26 of file Z3Solver.h.
getAllValidConfigurations()
Result< SolverErrorCode, std::vector< std::unique_ptr< vara::feature::Configuration > > > vara::solver::Z3Solver::getAllValidConfigurations () override virtual
Returns all valid configurations.
In comparison to getNumberValidConfigurations, this method returns the configurations instead of a number of configurations.
Returns
an error if an error occurs while retrieving the configurations. Otherwise, it will return the configurations.
Implements vara::solver::Solver.
Definition at line 200 of file Z3Solver.cpp.
References getCurrentConfiguration().
getCurrentConfiguration()
Result< SolverErrorCode, std::unique_ptr< vara::feature::Configuration > > vara::solver::Z3Solver::getCurrentConfiguration () override virtual
Returns the current configuration.
Returns
the current configuration found by the solver an error code in case of error.
Implements vara::solver::Solver.
Definition at line 254 of file Z3Solver.cpp.
References vara::solver::UNSAT.
Referenced by getAllValidConfigurations(), and getNextConfiguration().
getNextConfiguration()
Result< SolverErrorCode, std::unique_ptr< vara::feature::Configuration > > vara::solver::Z3Solver::getNextConfiguration () override virtual
This method returns the next configuration or an error in case of an error.
Returns
the next configuration or an error (e.g., if it is unsatisfiable).
Implements vara::solver::Solver.
Definition at line 179 of file Z3Solver.cpp.
References getCurrentConfiguration().
getNumberValidConfigurations()
Result< SolverErrorCode, uint64_t > vara::solver::Z3Solver::getNumberValidConfigurations () override virtual
Returns the number of valid configurations of the current constraint system (i.e., its features and its constraints).
In principle, this is a #SAT call (i.e., enumerating all configurations).
Returns
an error if the number of valid configurations can not be retried. This can be the case if there are still constraints left that were not included into the solver because of missing variables.
Implements vara::solver::Solver.
Definition at line 187 of file Z3Solver.cpp.
hasValidConfigurations()
Result< SolverErrorCode, bool > vara::solver::Z3Solver::hasValidConfigurations () override virtual
Returns true if the current constraint system (i.e., its features and its constraints) has valid configurations.
Returns
an error if, for instance, not all constraints could be parsed yet because of missing variables. Otherwise, it contains a boolean whether the current constraint system is solvable (true) or not (false).
Implements vara::solver::Solver.
Definition at line 171 of file Z3Solver.cpp.
removeFeature()
Result< SolverErrorCode > vara::solver::Z3Solver::removeFeature (feature::Feature & FeatureToRemove) override virtual
This method removes the given feature and all its constraints the feature is included in.
Note that this method may not be supported by some solvers.
Parameters
FeatureToRemove the feature that should be removed from the solver.
Returns
a possible error if removing the feature was not successful.
Implements vara::solver::Solver.
Definition at line 120 of file Z3Solver.cpp.
References vara::solver::NOT_SUPPORTED.
Friends And Related Function Documentation
Z3SolverConstraintVisitor
friend class Z3SolverConstraintVisitor friend
Definition at line 75 of file Z3Solver.h.
The documentation for this class was generated from the following files:
include/vara/Solver/Z3Solver.h
lib/Solver/Z3Solver.cpp