vara-feature: vara::feature::FeatureModelBuilder Class Reference
vara::feature::FeatureModelBuilder Class Reference
Builder for FeatureModel which can be used while parsing.
#include "vara/Feature/FeatureModelBuilder.h"
Public Member Functions
FeatureModelBuilder ()
FeatureModelBuilder (const FeatureModelBuilder &)=delete
FeatureModelBuilder & operator= (const FeatureModelBuilder &)=delete
FeatureModelBuilder (FeatureModelBuilder &&) noexcept=delete
FeatureModelBuilder & operator= (FeatureModelBuilder &&) noexcept=delete
~FeatureModelBuilder ()
template<typename FeatureTy , typename... Args, std::enable_if_t< std::is_base_of_v< Feature, FeatureTy >, bool > = true>
FeatureModelBuilder * makeFeature (std::string FeatureName, Args &&...FurtherArgs)
Try to create a new Feature.
FeatureModelBuilder * addEdge (const std::string &ParentName, const std::string &FeatureName)
FeatureModelBuilder * emplaceRelationship (Relationship::RelationshipKind RK, const std::string &ParentName)
FeatureModelBuilder * addConstraint (std::unique_ptr< FeatureModel::ConstraintTy > C)
FeatureModelBuilder * setVmName (std::string Name)
FeatureModelBuilder * setPath (const fs::path &Path)
FeatureModelBuilder * setCommit (std::string Commit)
FeatureModelBuilder * makeRoot (const std::string &Name)
std::unique_ptr< FeatureModel > buildFeatureModel ()
Build FeatureModel.
Detailed Description
Builder for FeatureModel which can be used while parsing.
Definition at line 16 of file FeatureModelBuilder.h.
Constructor & Destructor Documentation
FeatureModelBuilder() [1/3]
vara::feature::FeatureModelBuilder::FeatureModelBuilder () inline
Definition at line 18 of file FeatureModelBuilder.h.
FeatureModelBuilder() [2/3]
vara::feature::FeatureModelBuilder::FeatureModelBuilder (const FeatureModelBuilder &) delete
FeatureModelBuilder() [3/3]
vara::feature::FeatureModelBuilder::FeatureModelBuilder (FeatureModelBuilder &&) delete noexcept
~FeatureModelBuilder()
vara::feature::FeatureModelBuilder::~FeatureModelBuilder () inline
Definition at line 29 of file FeatureModelBuilder.h.
Member Function Documentation
addConstraint()
FeatureModelBuilder* vara::feature::FeatureModelBuilder::addConstraint (std::unique_ptr< FeatureModel::ConstraintTy > C) inline
Definition at line 65 of file FeatureModelBuilder.h.
Referenced by vara::feature::FeatureModel::clone().
addEdge()
FeatureModelBuilder* vara::feature::FeatureModelBuilder::addEdge (const std::string & ParentName, const std::string & FeatureName) inline
Definition at line 52 of file FeatureModelBuilder.h.
Referenced by vara::feature::FeatureModel::clone().
buildFeatureModel()
std::unique_ptr< FeatureModel > vara::feature::FeatureModelBuilder::buildFeatureModel ()
Build FeatureModel.
Returns
instance of FeatureModel
Definition at line 9 of file FeatureModelBuilder.cpp.
Referenced by vara::feature::FeatureModel::clone().
emplaceRelationship()
FeatureModelBuilder* vara::feature::FeatureModelBuilder::emplaceRelationship (Relationship::RelationshipKind RK, const std::string & ParentName) inline
Definition at line 58 of file FeatureModelBuilder.h.
Referenced by vara::feature::FeatureModel::clone().
makeFeature()
template<typename FeatureTy , typename... Args, std::enable_if_t< std::is_base_of_v< Feature, FeatureTy >, bool > = true> FeatureModelBuilder* vara::feature::FeatureModelBuilder::makeFeature (std::string FeatureName, Args &&... FurtherArgs) inline
Try to create a new Feature.
Parameters
[in] FeatureName name of the Feature
[in] FurtherArgs further arguments that should be passed to the Feature constructor
Returns
FeatureModelBuilder
Definition at line 45 of file FeatureModelBuilder.h.
Referenced by vara::feature::FeatureModel::clone().
makeRoot()
FeatureModelBuilder* vara::feature::FeatureModelBuilder::makeRoot (const std::string & Name) inline
Definition at line 85 of file FeatureModelBuilder.h.
Referenced by vara::feature::FeatureModel::clone().
operator=() [1/2]
FeatureModelBuilder& vara::feature::FeatureModelBuilder::operator= (const FeatureModelBuilder &) delete
operator=() [2/2]
FeatureModelBuilder& vara::feature::FeatureModelBuilder::operator= (FeatureModelBuilder &&) delete noexcept
setCommit()
FeatureModelBuilder* vara::feature::FeatureModelBuilder::setCommit (std::string Commit) inline
Definition at line 80 of file FeatureModelBuilder.h.
Referenced by vara::feature::FeatureModel::clone().
setPath()
FeatureModelBuilder* vara::feature::FeatureModelBuilder::setPath (const fs::path & Path) inline
Definition at line 75 of file FeatureModelBuilder.h.
Referenced by vara::feature::FeatureModel::clone().
setVmName()
FeatureModelBuilder* vara::feature::FeatureModelBuilder::setVmName (std::string Name) inline
Definition at line 70 of file FeatureModelBuilder.h.
Referenced by vara::feature::FeatureModel::clone().
The documentation for this class was generated from the following files:
include/vara/Feature/FeatureModelBuilder.h
lib/Feature/FeatureModelBuilder.cpp