vara-feature: vara::feature::Feature Class Reference
vara::feature::Feature Class Reference
Base class for components of FeatureModel.
#include "vara/Feature/Feature.h"
Public Types
enum FeatureKind { FeatureKind::FK_BINARY, FeatureKind::FK_NUMERIC, FeatureKind::FK_ROOT, FeatureKind::FK_UNKNOWN }
using locations_iterator = typename std::vector< FeatureSourceRange >::iterator
using constraint_iterator = typename std::vector< Constraint * >::iterator
using const_constraint_iterator = typename std::vector< Constraint * >::const_iterator
using excludes_iterator = typename std::vector< ExcludesConstraint * >::iterator
using const_excludes_iterator = typename std::vector< ExcludesConstraint * >::const_iterator
using implications_iterator = typename std::vector< ImpliesConstraint * >::iterator
using const_implications_iterator = typename std::vector< ImpliesConstraint * >::const_iterator
Public Types inherited from vara::feature::FeatureTreeNode
enum NodeKind { NodeKind::NK_FEATURE, NodeKind::NK_RELATIONSHIP }
using NodeSetType = typename llvm::SmallSet< FeatureTreeNode *, 3 >
Public Member Functions
Feature (std::string Name)
Feature (const Feature &)=delete
Feature & operator= (const Feature &)=delete
Feature (Feature &&)=delete
Feature & operator= (Feature &&)=delete
~Feature () override=default
std::size_t hash () const
FeatureKind getKind () const
llvm::StringRef getName () const
bool isOptional () const
Feature * getParentFeature () const
Search parent feature in tree structure – this may not exist or nullptr if node is already root.
bool operator== (const vara::feature::Feature &Other) const
Compare lowercase name assuming those are unique.
bool operator!= (const vara::feature::Feature &Other) const
bool operator< (const vara::feature::Feature &Other) const
Compare in depth first ordering.
bool operator> (const vara::feature::Feature &Other) const
bool hasLocations () const
void addLocation (FeatureSourceRange Fsr)
std::vector< FeatureSourceRange >::iterator removeLocation (const FeatureSourceRange &Fsr)
bool updateLocation (const FeatureSourceRange &OldFsr, FeatureSourceRange NewFsr)
std::vector< FeatureSourceRange >::iterator getLocationsBegin ()
std::vector< FeatureSourceRange >::iterator getLocationsEnd ()
llvm::iterator_range< locations_iterator > getLocations ()
llvm::iterator_range< constraint_iterator > constraints ()
llvm::iterator_range< const_constraint_iterator > constraints () const
llvm::iterator_range< excludes_iterator > excludes ()
llvm::iterator_range< const_excludes_iterator > excludes () const
llvm::iterator_range< implications_iterator > implications ()
llvm::iterator_range< const_implications_iterator > implications () const
virtual std::string toString () const
LLVM_DUMP_METHOD void dump () const
Public Member Functions inherited from vara::feature::FeatureTreeNode
FeatureTreeNode (NodeKind Kind)
FeatureTreeNode (FeatureTreeNode &)=delete
FeatureTreeNode & operator= (FeatureTreeNode &)=delete
FeatureTreeNode (FeatureTreeNode &&)=delete
FeatureTreeNode & operator= (FeatureTreeNode &&)=delete
virtual ~FeatureTreeNode ()=default
NodeKind getKind () const
FeatureTreeNode * getParent () const
bool hasEdgeFrom (FeatureTreeNode &N) const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
llvm::iterator_range< iterator > children ()
llvm::iterator_range< const_iterator > children () const
bool hasEdgeTo (const FeatureTreeNode &N) const
template<typename T = FeatureTreeNode>
llvm::SmallSet< T *, 3 > getChildren (int Depth=-1)
Search first (possibly transitive) children of given type in tree structure.
bool isLeaf ()
Checks if a FeatureTreeNode has children or is a leaf.
Static Public Member Functions
static bool classof (const FeatureTreeNode *N)
Protected Member Functions
Feature (FeatureKind Kind, string Name, bool Opt, std::vector< FeatureSourceRange > Locations, FeatureTreeNode *Parent=nullptr, const NodeSetType &Children={})
Protected Member Functions inherited from vara::feature::FeatureTreeNode
FeatureTreeNode (NodeKind Kind, FeatureTreeNode *Parent, const llvm::SmallPtrSetImpl< FeatureTreeNode * > &Children)
FeatureTreeNode (NodeKind Kind, FeatureTreeNode *Parent, const std::vector< FeatureTreeNode * > &Children)
Friends
class FeatureModel
class FeatureModelBuilder
class detail::FeatureModelModification
Detailed Description
Base class for components of FeatureModel.
Definition at line 34 of file Feature.h.
Member Typedef Documentation
const_constraint_iterator
using vara::feature::Feature::const_constraint_iterator = typename std::vector<Constraint *>::const_iterator
Definition at line 130 of file Feature.h.
const_excludes_iterator
using vara::feature::Feature::const_excludes_iterator = typename std::vector<ExcludesConstraint *>::const_iterator
Definition at line 146 of file Feature.h.
const_implications_iterator
using vara::feature::Feature::const_implications_iterator = typename std::vector<ImpliesConstraint *>::const_iterator
Definition at line 161 of file Feature.h.
constraint_iterator
using vara::feature::Feature::constraint_iterator = typename std::vector<Constraint *>::iterator
Definition at line 128 of file Feature.h.
excludes_iterator
using vara::feature::Feature::excludes_iterator = typename std::vector<ExcludesConstraint *>::iterator
Definition at line 144 of file Feature.h.
implications_iterator
using vara::feature::Feature::implications_iterator = typename std::vector<ImpliesConstraint *>::iterator
Definition at line 159 of file Feature.h.
locations_iterator
using vara::feature::Feature::locations_iterator = typename std::vector<FeatureSourceRange>::iterator
Definition at line 120 of file Feature.h.
Member Enumeration Documentation
FeatureKind
enum vara::feature::Feature::FeatureKind strong
Enumerator
FK_BINARY
FK_NUMERIC
FK_ROOT
FK_UNKNOWN
Definition at line 40 of file Feature.h.
Constructor & Destructor Documentation
Feature() [1/4]
vara::feature::Feature::Feature (std::string Name) inline
Definition at line 42 of file Feature.h.
Feature() [2/4]
vara::feature::Feature::Feature (const Feature &) delete
Feature() [3/4]
vara::feature::Feature::Feature (Feature &&) delete
~Feature()
vara::feature::Feature::~Feature () override default
Feature() [4/4]
vara::feature::Feature::Feature (FeatureKind Kind, string Name, bool Opt, std::vector< FeatureSourceRange > Locations, FeatureTreeNode * Parent = nullptr, const NodeSetType & Children = {}) inline protected
Definition at line 184 of file Feature.h.
Member Function Documentation
addLocation()
void vara::feature::Feature::addLocation (FeatureSourceRange Fsr) inline
Definition at line 95 of file Feature.h.
Referenced by vara::feature::detail::FeatureModelModification::addLocation().
classof()
static bool vara::feature::Feature::classof (const FeatureTreeNode * N) inline static
Definition at line 179 of file Feature.h.
References vara::feature::FeatureTreeNode::getKind(), and vara::feature::FeatureTreeNode::NK_FEATURE.
constraints() [1/2]
llvm::iterator_range<constraint_iterator> vara::feature::Feature::constraints () inline
Definition at line 132 of file Feature.h.
Referenced by llvm::GraphWriter< vara::feature::FeatureModel * >::buildFeatureLabel().
constraints() [2/2]
llvm::iterator_range<const_constraint_iterator> vara::feature::Feature::constraints () const inline
Definition at line 136 of file Feature.h.
dump()
LLVM_DUMP_METHOD void vara::feature::Feature::dump () const inline
Definition at line 177 of file Feature.h.
References toString().
Referenced by vara::feature::FeatureModel::dump().
excludes() [1/2]
llvm::iterator_range<excludes_iterator> vara::feature::Feature::excludes () inline
Definition at line 148 of file Feature.h.
Referenced by vara::feature::detectExclude().
excludes() [2/2]
llvm::iterator_range<const_excludes_iterator> vara::feature::Feature::excludes () const inline
Definition at line 151 of file Feature.h.
getKind()
FeatureKind vara::feature::Feature::getKind () const inline
Definition at line 55 of file Feature.h.
Referenced by vara::feature::BinaryFeature::classof(), vara::feature::NumericFeature::classof(), vara::feature::RootFeature::classof(), vara::feature::compareProperties(), and vara::feature::featureCopy().
getLocations()
llvm::iterator_range<locations_iterator> vara::feature::Feature::getLocations () inline
Definition at line 121 of file Feature.h.
Referenced by llvm::GraphWriter< vara::feature::FeatureModel * >::buildFeatureLabel(), and vara::feature::mergeSubtree().
getLocationsBegin()
std::vector<FeatureSourceRange>::iterator vara::feature::Feature::getLocationsBegin () inline
Definition at line 114 of file Feature.h.
Referenced by vara::feature::featureCopy().
getLocationsEnd()
std::vector<FeatureSourceRange>::iterator vara::feature::Feature::getLocationsEnd () inline
Definition at line 117 of file Feature.h.
Referenced by vara::feature::featureCopy().
getName()
llvm::StringRef vara::feature::Feature::getName () const inline
Definition at line 57 of file Feature.h.
Referenced by llvm::GraphWriter< vara::feature::FeatureModel * >::buildFeatureLabel(), vara::feature::compareProperties(), vara::feature::featureCopy(), hash(), vara::feature::mergeSubtree(), vara::feature::detail::SetRoot::operator()(), operator<(), operator==(), and toString().
getParentFeature()
Feature* vara::feature::Feature::getParentFeature () const inline
Search parent feature in tree structure – this may not exist or nullptr if node is already root.
Definition at line 63 of file Feature.h.
References vara::feature::FeatureTreeNode::getParent().
Referenced by vara::feature::compareProperties(), vara::feature::mergeSubtree(), operator<(), and toString().
hash()
std::size_t vara::feature::Feature::hash () const inline
Definition at line 51 of file Feature.h.
References getName().
hasLocations()
bool vara::feature::Feature::hasLocations () const inline
Definition at line 93 of file Feature.h.
Referenced by llvm::GraphWriter< vara::feature::FeatureModel * >::buildFeatureLabel(), and toString().
implications() [1/2]
llvm::iterator_range<implications_iterator> vara::feature::Feature::implications () inline
Definition at line 163 of file Feature.h.
implications() [2/2]
llvm::iterator_range<const_implications_iterator> vara::feature::Feature::implications () const inline
Definition at line 167 of file Feature.h.
isOptional()
bool vara::feature::Feature::isOptional () const inline
Definition at line 59 of file Feature.h.
Referenced by vara::feature::compareProperties(), and vara::feature::featureCopy().
operator!=()
bool vara::feature::Feature::operator!= (const vara::feature::Feature & Other) const inline
Definition at line 81 of file Feature.h.
References operator==().
operator<()
bool vara::feature::Feature::operator< (const vara::feature::Feature & Other) const
Compare in depth first ordering.
Find roots of subtrees containing either A (this) or B (Other) which have a common parent feature and compare them lexicographically.
If no such node can be found compare names directly.
Definition at line 53 of file Feature.cpp.
References getName(), and getParentFeature().
operator=() [1/2]
Feature& vara::feature::Feature::operator= (const Feature &) delete
operator=() [2/2]
Feature& vara::feature::Feature::operator= (Feature &&) delete
operator==()
bool vara::feature::Feature::operator== (const vara::feature::Feature & Other) const inline
Compare lowercase name assuming those are unique.
Definition at line 77 of file Feature.h.
References getName().
Referenced by operator!=().
operator>()
bool vara::feature::Feature::operator> (const vara::feature::Feature & Other) const inline
Definition at line 87 of file Feature.h.
removeLocation()
std::vector<FeatureSourceRange>::iterator vara::feature::Feature::removeLocation (const FeatureSourceRange & Fsr) inline
Definition at line 100 of file Feature.h.
Referenced by vara::feature::detail::FeatureModelModification::removeLocation().
toString()
std::string vara::feature::Feature::toString () const virtual
Reimplemented in vara::feature::NumericFeature, and vara::feature::BinaryFeature.
Definition at line 7 of file Feature.cpp.
References vara::feature::FeatureTreeNode::children(), getName(), getParentFeature(), and hasLocations().
Referenced by dump(), operator<<(), vara::feature::BinaryFeature::toString(), and vara::feature::NumericFeature::toString().
updateLocation()
bool vara::feature::Feature::updateLocation (const FeatureSourceRange & OldFsr, FeatureSourceRange NewFsr) inline
Definition at line 104 of file Feature.h.
Friends And Related Function Documentation
detail::FeatureModelModification
friend class detail::FeatureModelModification friend
Definition at line 37 of file Feature.h.
FeatureModel
friend class FeatureModel friend
Definition at line 35 of file Feature.h.
FeatureModelBuilder
friend class FeatureModelBuilder friend
Definition at line 36 of file Feature.h.
The documentation for this class was generated from the following files:
include/vara/Feature/Feature.h
lib/Feature/Feature.cpp