vara-feature: vara::feature::FeatureSourceRange::FeatureMemberOffset Class Reference
vara::feature::FeatureSourceRange::FeatureMemberOffset Class Reference
#include "vara/Feature/FeatureSourceRange.h"
Public Member Functions
void setMemberOffset (std::string MemberOffset)
std::string fullMemberOffset () const
llvm::StringRef className () const
llvm::StringRef memberName () const
std::string toString () const
bool operator== (const FeatureMemberOffset &Other) const
bool operator!= (const FeatureMemberOffset &Other) const
Static Public Member Functions
static llvm::Optional< FeatureMemberOffset > createFeatureMemberOffset (std::string MemberOffset)
static bool isInMemberOffsetFormat (llvm::StringRef PossibleMemberOffset)
Detailed Description
Definition at line 74 of file FeatureSourceRange.h.
Member Function Documentation
className()
llvm::StringRef vara::feature::FeatureSourceRange::FeatureMemberOffset::className () const inline
Definition at line 103 of file FeatureSourceRange.h.
createFeatureMemberOffset()
static llvm::Optional<FeatureMemberOffset> vara::feature::FeatureSourceRange::FeatureMemberOffset::createFeatureMemberOffset (std::string MemberOffset) inline static
Definition at line 80 of file FeatureSourceRange.h.
References isInMemberOffsetFormat().
fullMemberOffset()
std::string vara::feature::FeatureSourceRange::FeatureMemberOffset::fullMemberOffset () const inline
Definition at line 99 of file FeatureSourceRange.h.
Referenced by operator!=(), operator==(), and toString().
isInMemberOffsetFormat()
static bool vara::feature::FeatureSourceRange::FeatureMemberOffset::isInMemberOffsetFormat (llvm::StringRef PossibleMemberOffset) inline static
Definition at line 89 of file FeatureSourceRange.h.
Referenced by createFeatureMemberOffset(), and setMemberOffset().
memberName()
llvm::StringRef vara::feature::FeatureSourceRange::FeatureMemberOffset::memberName () const inline
Definition at line 108 of file FeatureSourceRange.h.
operator!=()
bool vara::feature::FeatureSourceRange::FeatureMemberOffset::operator!= (const FeatureMemberOffset & Other) const inline
Definition at line 119 of file FeatureSourceRange.h.
References fullMemberOffset().
operator==()
bool vara::feature::FeatureSourceRange::FeatureMemberOffset::operator== (const FeatureMemberOffset & Other) const inline
Definition at line 115 of file FeatureSourceRange.h.
References fullMemberOffset().
setMemberOffset()
void vara::feature::FeatureSourceRange::FeatureMemberOffset::setMemberOffset (std::string MemberOffset) inline
Definition at line 94 of file FeatureSourceRange.h.
References isInMemberOffsetFormat().
toString()
std::string vara::feature::FeatureSourceRange::FeatureMemberOffset::toString () const inline
Definition at line 113 of file FeatureSourceRange.h.
References fullMemberOffset().
The documentation for this class was generated from the following file:
include/vara/Feature/FeatureSourceRange.h