vara-feature: vara::feature::FeatureSourceRange::FeatureSourceLocation Class Reference
vara::feature::FeatureSourceRange::FeatureSourceLocation Class Reference
#include "vara/Feature/FeatureSourceRange.h"
Public Member Functions
FeatureSourceLocation (int Line, int Column)
FeatureSourceLocation (const FeatureSourceLocation &L)=default
FeatureSourceLocation & operator= (const FeatureSourceLocation &)=default
FeatureSourceLocation (FeatureSourceLocation &&)=default
FeatureSourceLocation & operator= (FeatureSourceLocation &&)=default
virtual ~FeatureSourceLocation ()=default
void setLineNumber (int LineNumber)
int getLineNumber () const
void setColumnOffset (int ColumnOffset)
int getColumnOffset () const
std::string toString () const
bool operator== (const FeatureSourceLocation &Other) const
bool operator< (const FeatureSourceLocation &Other) const
bool operator> (const FeatureSourceLocation &Other) const
Detailed Description
Definition at line 30 of file FeatureSourceRange.h.
Constructor & Destructor Documentation
FeatureSourceLocation() [1/3]
vara::feature::FeatureSourceRange::FeatureSourceLocation::FeatureSourceLocation (int Line, int Column) inline
Definition at line 33 of file FeatureSourceRange.h.
FeatureSourceLocation() [2/3]
vara::feature::FeatureSourceRange::FeatureSourceLocation::FeatureSourceLocation (const FeatureSourceLocation & L) default
FeatureSourceLocation() [3/3]
vara::feature::FeatureSourceRange::FeatureSourceLocation::FeatureSourceLocation (FeatureSourceLocation &&) default
~FeatureSourceLocation()
virtual vara::feature::FeatureSourceRange::FeatureSourceLocation::~FeatureSourceLocation () virtual default
Member Function Documentation
getColumnOffset()
int vara::feature::FeatureSourceRange::FeatureSourceLocation::getColumnOffset () const inline
Definition at line 44 of file FeatureSourceRange.h.
Referenced by operator<(), operator==(), and toString().
getLineNumber()
int vara::feature::FeatureSourceRange::FeatureSourceLocation::getLineNumber () const inline
Definition at line 41 of file FeatureSourceRange.h.
Referenced by operator<(), operator==(), and toString().
operator<()
bool vara::feature::FeatureSourceRange::FeatureSourceLocation::operator< (const FeatureSourceLocation & Other) const inline
Definition at line 55 of file FeatureSourceRange.h.
References getColumnOffset(), and getLineNumber().
operator=() [1/2]
FeatureSourceLocation& vara::feature::FeatureSourceRange::FeatureSourceLocation::operator= (const FeatureSourceLocation &) default
operator=() [2/2]
FeatureSourceLocation& vara::feature::FeatureSourceRange::FeatureSourceLocation::operator= (FeatureSourceLocation &&) default
operator==()
bool vara::feature::FeatureSourceRange::FeatureSourceLocation::operator== (const FeatureSourceLocation & Other) const inline
Definition at line 50 of file FeatureSourceRange.h.
References getColumnOffset(), and getLineNumber().
operator>()
bool vara::feature::FeatureSourceRange::FeatureSourceLocation::operator> (const FeatureSourceLocation & Other) const inline
Definition at line 61 of file FeatureSourceRange.h.
setColumnOffset()
void vara::feature::FeatureSourceRange::FeatureSourceLocation::setColumnOffset (int ColumnOffset) inline
Definition at line 43 of file FeatureSourceRange.h.
setLineNumber()
void vara::feature::FeatureSourceRange::FeatureSourceLocation::setLineNumber (int LineNumber) inline
Definition at line 40 of file FeatureSourceRange.h.
toString()
std::string vara::feature::FeatureSourceRange::FeatureSourceLocation::toString () const inline
Definition at line 46 of file FeatureSourceRange.h.
References getColumnOffset(), and getLineNumber().
The documentation for this class was generated from the following file:
include/vara/Feature/FeatureSourceRange.h