vara-feature: vara::feature::deprecated::OrderedFeatureVector Class Reference
vara::feature::deprecated::OrderedFeatureVector Class Reference
Always ordered vector of features comparing with Feature::operator<.
#include "vara/Feature/OrderedFeatureVector.h"
Public Types
using ordered_feature_iterator = typename llvm::SmallVector< Feature *, 3 >::iterator
using const_ordered_feature_iterator = typename llvm::SmallVector< Feature *, 3 >::const_iterator
Public Member Functions
OrderedFeatureVector ()=default
OrderedFeatureVector (std::initializer_list< Feature * > Init)
template<class FeatureIterTy >
OrderedFeatureVector (FeatureIterTy &&Begin, FeatureIterTy &&End)
OrderedFeatureVector (const OrderedFeatureVector &OFV)=delete
OrderedFeatureVector & operator= (const OrderedFeatureVector &)=delete
OrderedFeatureVector (OrderedFeatureVector &&)=delete
OrderedFeatureVector & operator= (OrderedFeatureVector &&)=delete
~OrderedFeatureVector ()=default
void insert (Feature *F)
Insert feature while preserving ordering.
void remove (Feature *F)
Remove feature.
template<class FeatureIterTy >
void insert (llvm::iterator_range< FeatureIterTy > Iter)
template<class FeatureIterTy >
void insert (FeatureIterTy &&Begin, FeatureIterTy &&End)
void insert (std::initializer_list< Feature * > Init)
unsigned int size ()
bool empty ()
ordered_feature_iterator begin ()
const_ordered_feature_iterator begin () const
ordered_feature_iterator end ()
const_ordered_feature_iterator end () const
Detailed Description
Always ordered vector of features comparing with Feature::operator<.
Definition at line 16 of file OrderedFeatureVector.h.
Member Typedef Documentation
const_ordered_feature_iterator
using vara::feature::deprecated::OrderedFeatureVector::const_ordered_feature_iterator = typename llvm::SmallVector<Feature *, 3>::const_iterator
Definition at line 21 of file OrderedFeatureVector.h.
ordered_feature_iterator
using vara::feature::deprecated::OrderedFeatureVector::ordered_feature_iterator = typename llvm::SmallVector<Feature *, 3>::iterator
Definition at line 19 of file OrderedFeatureVector.h.
Constructor & Destructor Documentation
OrderedFeatureVector() [1/5]
vara::feature::deprecated::OrderedFeatureVector::OrderedFeatureVector () default
OrderedFeatureVector() [2/5]
vara::feature::deprecated::OrderedFeatureVector::OrderedFeatureVector (std::initializer_list< Feature * > Init) inline
Definition at line 24 of file OrderedFeatureVector.h.
References insert().
OrderedFeatureVector() [3/5]
template<class FeatureIterTy > vara::feature::deprecated::OrderedFeatureVector::OrderedFeatureVector (FeatureIterTy && Begin, FeatureIterTy && End) inline
Definition at line 26 of file OrderedFeatureVector.h.
References insert().
OrderedFeatureVector() [4/5]
vara::feature::deprecated::OrderedFeatureVector::OrderedFeatureVector (const OrderedFeatureVector & OFV) delete
OrderedFeatureVector() [5/5]
vara::feature::deprecated::OrderedFeatureVector::OrderedFeatureVector (OrderedFeatureVector &&) delete
~OrderedFeatureVector()
vara::feature::deprecated::OrderedFeatureVector::~OrderedFeatureVector () default
Member Function Documentation
begin() [1/2]
ordered_feature_iterator vara::feature::deprecated::OrderedFeatureVector::begin () inline
Definition at line 66 of file OrderedFeatureVector.h.
begin() [2/2]
const_ordered_feature_iterator vara::feature::deprecated::OrderedFeatureVector::begin () const inline
Definition at line 67 of file OrderedFeatureVector.h.
empty()
bool vara::feature::deprecated::OrderedFeatureVector::empty () inline
Definition at line 64 of file OrderedFeatureVector.h.
end() [1/2]
ordered_feature_iterator vara::feature::deprecated::OrderedFeatureVector::end () inline
Definition at line 71 of file OrderedFeatureVector.h.
end() [2/2]
const_ordered_feature_iterator vara::feature::deprecated::OrderedFeatureVector::end () const inline
Definition at line 72 of file OrderedFeatureVector.h.
insert() [1/4]
void vara::feature::deprecated::OrderedFeatureVector::insert (Feature * F)
Insert feature while preserving ordering.
Definition at line 7 of file OrderedFeatureVector.cpp.
Referenced by insert(), and OrderedFeatureVector().
insert() [2/4]
template<class FeatureIterTy > void vara::feature::deprecated::OrderedFeatureVector::insert (FeatureIterTy && Begin, FeatureIterTy && End) inline
Definition at line 53 of file OrderedFeatureVector.h.
References insert().
insert() [3/4]
template<class FeatureIterTy > void vara::feature::deprecated::OrderedFeatureVector::insert (llvm::iterator_range< FeatureIterTy > Iter) inline
Definition at line 46 of file OrderedFeatureVector.h.
References insert().
insert() [4/4]
void vara::feature::deprecated::OrderedFeatureVector::insert (std::initializer_list< Feature * > Init) inline
Definition at line 58 of file OrderedFeatureVector.h.
References insert().
operator=() [1/2]
OrderedFeatureVector& vara::feature::deprecated::OrderedFeatureVector::operator= (const OrderedFeatureVector &) delete
operator=() [2/2]
OrderedFeatureVector& vara::feature::deprecated::OrderedFeatureVector::operator= (OrderedFeatureVector &&) delete
remove()
void vara::feature::deprecated::OrderedFeatureVector::remove (Feature * F) inline
Remove feature.
Definition at line 40 of file OrderedFeatureVector.h.
size()
unsigned int vara::feature::deprecated::OrderedFeatureVector::size () inline
Definition at line 62 of file OrderedFeatureVector.h.
The documentation for this class was generated from the following files:
include/vara/Feature/OrderedFeatureVector.h
lib/Feature/OrderedFeatureVector.cpp