vara-feature: vara::feature::detail::FeatureModelModifyTransactionBase Class Reference
vara::feature::detail::FeatureModelModifyTransactionBase Class Reference
#include "vara/Feature/FeatureModelTransaction.h"
Protected Member Functions
FeatureModelModifyTransactionBase (FeatureModel &FM)
Result< FTErrorCode > commitImpl ()
void abortImpl ()
bool isUncommitted () const
void addFeatureImpl (std::unique_ptr< Feature > NewFeature, Feature *Parent)
void removeFeatureImpl (FeatureVariantTy &F, bool Recursive=false)
void addRelationshipImpl (Relationship::RelationshipKind Kind, const FeatureVariantTy &Parent)
void removeRelationshipImpl (const FeatureVariantTy &F)
void addLocationImpl (const FeatureVariantTy &F, FeatureSourceRange FSR)
void removeLocationImpl (const FeatureVariantTy &F, FeatureSourceRange &FSR)
void addConstraintImpl (std::unique_ptr< Constraint > NewConstraint)
void setNameImpl (std::string Name)
void setCommitImpl (std::string Commit)
void setPathImpl (fs::path Path)
void setRootImpl (std::unique_ptr< RootFeature > Root)
void addChildImpl (const FeatureTreeNodeVariantTy &Parent, const FeatureTreeNodeVariantTy &Child)
Detailed Description
Definition at line 945 of file FeatureModelTransaction.h.
Constructor & Destructor Documentation
FeatureModelModifyTransactionBase()
vara::feature::detail::FeatureModelModifyTransactionBase::FeatureModelModifyTransactionBase (FeatureModel & FM) inline protected
Definition at line 947 of file FeatureModelTransaction.h.
Member Function Documentation
abortImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::abortImpl () inline protected
Definition at line 970 of file FeatureModelTransaction.h.
Referenced by commitImpl().
addChildImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::addChildImpl (const FeatureTreeNodeVariantTy & Parent, const FeatureTreeNodeVariantTy & Child) inline protected
Definition at line 1055 of file FeatureModelTransaction.h.
addConstraintImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::addConstraintImpl (std::unique_ptr< Constraint > NewConstraint) inline protected
Definition at line 1017 of file FeatureModelTransaction.h.
addFeatureImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::addFeatureImpl (std::unique_ptr< Feature > NewFeature, Feature * Parent) inline protected
Definition at line 982 of file FeatureModelTransaction.h.
addLocationImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::addLocationImpl (const FeatureVariantTy & F, FeatureSourceRange FSR) inline protected
Definition at line 1006 of file FeatureModelTransaction.h.
addRelationshipImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::addRelationshipImpl (Relationship::RelationshipKind Kind, const FeatureVariantTy & Parent) inline protected
Definition at line 995 of file FeatureModelTransaction.h.
References vara::feature::detail::FeatureModelModification::makeUniqueModification().
commitImpl()
Result<FTErrorCode> vara::feature::detail::FeatureModelModifyTransactionBase::commitImpl () inline protected
Definition at line 949 of file FeatureModelTransaction.h.
References vara::feature::ABORTED, abortImpl(), vara::feature::FeatureModelConsistencyChecker< Rules >::isFeatureModelValid(), and isUncommitted().
isUncommitted()
bool vara::feature::detail::FeatureModelModifyTransactionBase::isUncommitted () const inline protected
Definition at line 975 of file FeatureModelTransaction.h.
Referenced by commitImpl().
removeFeatureImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::removeFeatureImpl (FeatureVariantTy & F, bool Recursive = false) inline protected
Definition at line 990 of file FeatureModelTransaction.h.
References vara::feature::detail::FeatureModelModification::makeUniqueModification().
removeLocationImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::removeLocationImpl (const FeatureVariantTy & F, FeatureSourceRange & FSR) inline protected
Definition at line 1012 of file FeatureModelTransaction.h.
References vara::feature::detail::FeatureModelModification::makeUniqueModification().
removeRelationshipImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::removeRelationshipImpl (const FeatureVariantTy & F) inline protected
Definition at line 1001 of file FeatureModelTransaction.h.
References vara::feature::detail::FeatureModelModification::makeUniqueModification().
setCommitImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::setCommitImpl (std::string Commit) inline protected
Definition at line 1031 of file FeatureModelTransaction.h.
setNameImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::setNameImpl (std::string Name) inline protected
Definition at line 1023 of file FeatureModelTransaction.h.
setPathImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::setPathImpl (fs::path Path) inline protected
Definition at line 1039 of file FeatureModelTransaction.h.
setRootImpl()
void vara::feature::detail::FeatureModelModifyTransactionBase::setRootImpl (std::unique_ptr< RootFeature > Root) inline protected
Definition at line 1047 of file FeatureModelTransaction.h.
The documentation for this class was generated from the following file:
include/vara/Feature/FeatureModelTransaction.h