vara-feature: Result< ErrorTy, ValueTy > Class Template Reference
Result< ErrorTy, ValueTy > Class Template Reference
#include "vara/Utils/Result.h"
Public Member Functions
Result (Ok< ValueTy > V)
Result (Error< ErrorTy > E)
template<typename... ArgsTy, std::enable_if_t< std::is_constructible_v< ValueTy, ArgsTy... >, bool > = true>
Result (ArgsTy &&...Args)
template<typename... ArgsTy, std::enable_if_t< std::is_constructible_v< ErrorTy, ArgsTy... >, bool > = true>
Result (ArgsTy &&...Args)
operator bool () const
Return false if there is an error.
ValueTy operator* () &
ValueTy operator* () &&
ValueTy extract_value ()
ErrorTy getError () &
ErrorTy getError () &&
ErrorTy extract_error ()
Protected Attributes
std::variant< Ok< ValueTy >, Error< ErrorTy > > Variant
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Result< ErrorTy, ValueTy > &R)
Detailed Description
template<typename ErrorTy, typename ValueTy = void>
class Result< ErrorTy, ValueTy >
Definition at line 90 of file Result.h.
Constructor & Destructor Documentation
Result() [1/4]
template<typename ErrorTy , typename ValueTy = void> Result< ErrorTy, ValueTy >::Result (Ok< ValueTy > V) inline
Definition at line 92 of file Result.h.
Result() [2/4]
template<typename ErrorTy , typename ValueTy = void> Result< ErrorTy, ValueTy >::Result (Error< ErrorTy > E) inline
Definition at line 94 of file Result.h.
Result() [3/4]
template<typename ErrorTy , typename ValueTy = void> template<typename... ArgsTy, std::enable_if_t< std::is_constructible_v< ValueTy, ArgsTy... >, bool > = true> Result< ErrorTy, ValueTy >::Result (ArgsTy &&... Args) inline
Definition at line 99 of file Result.h.
Result() [4/4]
template<typename ErrorTy , typename ValueTy = void> template<typename... ArgsTy, std::enable_if_t< std::is_constructible_v< ErrorTy, ArgsTy... >, bool > = true> Result< ErrorTy, ValueTy >::Result (ArgsTy &&... Args) inline
Definition at line 106 of file Result.h.
Member Function Documentation
extract_error()
template<typename ErrorTy , typename ValueTy = void> ErrorTy Result< ErrorTy, ValueTy >::extract_error () inline
Definition at line 134 of file Result.h.
References Result< ErrorTy, ValueTy >::Variant.
Referenced by Result< ErrorTy, ValueTy >::getError().
extract_value()
template<typename ErrorTy , typename ValueTy = void> ValueTy Result< ErrorTy, ValueTy >::extract_value () inline
Definition at line 122 of file Result.h.
References Result< ErrorTy, ValueTy >::Variant.
Referenced by Result< ErrorTy, ValueTy >::operator*().
getError() [1/2]
template<typename ErrorTy , typename ValueTy = void> ErrorTy Result< ErrorTy, ValueTy >::getError () & inline
Definition at line 127 of file Result.h.
References Result< ErrorTy, ValueTy >::Variant.
getError() [2/2]
template<typename ErrorTy , typename ValueTy = void> ErrorTy Result< ErrorTy, ValueTy >::getError () && inline
Definition at line 132 of file Result.h.
References Result< ErrorTy, ValueTy >::extract_error().
operator bool()
template<typename ErrorTy , typename ValueTy = void> Result< ErrorTy, ValueTy >::operator bool () const inline
Return false if there is an error.
Definition at line 111 of file Result.h.
References Result< ErrorTy, ValueTy >::Variant.
operator*() [1/2]
template<typename ErrorTy , typename ValueTy = void> ValueTy Result< ErrorTy, ValueTy >::operator* () & inline
Definition at line 115 of file Result.h.
References Result< ErrorTy, ValueTy >::Variant.
operator*() [2/2]
template<typename ErrorTy , typename ValueTy = void> ValueTy Result< ErrorTy, ValueTy >::operator* () && inline
Definition at line 120 of file Result.h.
References Result< ErrorTy, ValueTy >::extract_value().
Friends And Related Function Documentation
operator<<
template<typename ErrorTy , typename ValueTy = void> llvm::raw_ostream& operator<< (llvm::raw_ostream & OS, const Result< ErrorTy, ValueTy > & R) friend
Definition at line 139 of file Result.h.
Member Data Documentation
Variant
template<typename ErrorTy , typename ValueTy = void> std::variant<Ok<ValueTy>, Error<ErrorTy> > Result< ErrorTy, ValueTy >::Variant protected
Definition at line 146 of file Result.h.
Referenced by Result< ErrorTy, ValueTy >::extract_error(), Result< ErrorTy, ValueTy >::extract_value(), Result< ErrorTy, ValueTy >::getError(), Result< ErrorTy, ValueTy >::operator bool(), and Result< ErrorTy, ValueTy >::operator*().
The documentation for this class was generated from the following file:
include/vara/Utils/Result.h