vara-feature: vara::feature::ConfigurationOption Class Reference
vara::feature::ConfigurationOption Class Reference
This class represents a simple configuration option.
#include "vara/Configuration/Configuration.h"
Public Member Functions
virtual ~ConfigurationOption ()=default
ConfigurationOption (llvm::StringRef Name, llvm::StringRef Value)
The constructor of a configuration options takes the name and the value as an argument.
llvm::StringRef name () const
This method returns the name of the configuration option.
llvm::Optional< llvm::StringRef > stringValue () const
This method returns the string value of the configuration option.
llvm::Optional< bool > boolValue () const
This method returns the boolean value of the configuration option.
llvm::Optional< int64_t > intValue () const
This method returns the integer value of the configuration option.
std::string asString () const
This method returns the value as string no matter what the real type is.
std::string toString () const
This method returns the string representation of this configuration option.
bool isBool () const
This method returns true if the value is a boolean value.
bool isString () const
This method returns true if the value is a string.
bool isInt () const
This method returns true if the value is an integer.
Detailed Description
This class represents a simple configuration option.
Note that this class is not linked to real features from the feature model and does also not check the type and the value of the given option.
Definition at line 19 of file Configuration.h.
Constructor & Destructor Documentation
~ConfigurationOption()
virtual vara::feature::ConfigurationOption::~ConfigurationOption () virtual default
ConfigurationOption()
vara::feature::ConfigurationOption::ConfigurationOption (llvm::StringRef Name, llvm::StringRef Value) inline
The constructor of a configuration options takes the name and the value as an argument.
The name and the value do not change over time.
Definition at line 25 of file Configuration.h.
Member Function Documentation
asString()
std::string vara::feature::ConfigurationOption::asString () const inline
This method returns the value as string no matter what the real type is.
Returns
the value as string
Definition at line 62 of file Configuration.h.
References boolValue(), intValue(), isBool(), isString(), and stringValue().
Referenced by toString().
boolValue()
llvm::Optional<bool> vara::feature::ConfigurationOption::boolValue () const inline
This method returns the boolean value of the configuration option.
Returns
the boolean value of the configuration option as a bool
Definition at line 44 of file Configuration.h.
References isBool().
Referenced by asString().
intValue()
llvm::Optional<int64_t> vara::feature::ConfigurationOption::intValue () const inline
This method returns the integer value of the configuration option.
Returns
the integer value of the configuration option as an int64_t
Definition at line 53 of file Configuration.h.
References isInt().
Referenced by asString().
isBool()
bool vara::feature::ConfigurationOption::isBool () const inline
This method returns true if the value is a boolean value.
Returns
whether the value of the configuration option is a boolean value
Definition at line 84 of file Configuration.h.
Referenced by asString(), and boolValue().
isInt()
bool vara::feature::ConfigurationOption::isInt () const inline
This method returns true if the value is an integer.
Returns
whether the value of the configuration option is an integer
Definition at line 96 of file Configuration.h.
Referenced by intValue().
isString()
bool vara::feature::ConfigurationOption::isString () const inline
This method returns true if the value is a string.
Returns
whether the value of the configuration option is a string
Definition at line 90 of file Configuration.h.
Referenced by asString(), and stringValue().
name()
llvm::StringRef vara::feature::ConfigurationOption::name () const inline
This method returns the name of the configuration option.
Returns
the name of the configuration option as a string
Definition at line 30 of file Configuration.h.
stringValue()
llvm::Optional<llvm::StringRef> vara::feature::ConfigurationOption::stringValue () const inline
This method returns the string value of the configuration option.
Returns
the string value of the configuration option as a string
Definition at line 34 of file Configuration.h.
References isString().
Referenced by asString().
toString()
std::string vara::feature::ConfigurationOption::toString () const inline
This method returns the string representation of this configuration option.
Returns
the string representation in the format: name: value
Definition at line 78 of file Configuration.h.
References asString().
The documentation for this class was generated from the following file:
include/vara/Configuration/Configuration.h