vara-feature: vara::feature::GreaterConstraint Class Reference
vara::feature::GreaterConstraint Class Reference
#include "vara/Feature/Constraint.h"
Public Member Functions
GreaterConstraint (std::unique_ptr< Constraint > LeftOperand, std::unique_ptr< Constraint > RightOperand)
std::unique_ptr< Constraint > clone () override
Recursively clones constraint tree.
std::string toString () const override
std::string toHTML () const override
Public Member Functions inherited from vara::feature::BinaryConstraint
BinaryConstraint (ConstraintKind Kind, std::unique_ptr< Constraint > LeftOperand, std::unique_ptr< Constraint > RightOperand)
Constraint * getLeftOperand () const
Constraint * getRightOperand () const
bool accept (ConstraintVisitor &V) override
Public Member Functions inherited from vara::feature::Constraint
Constraint (ConstraintKind Kind)
Constraint (const Constraint &)=delete
Constraint & operator= (Constraint &)=delete
Constraint (Constraint &&)=delete
Constraint & operator= (Constraint &&)=delete
virtual ~Constraint ()=default
ConstraintKind getKind () const
void setParent (Constraint *P)
Constraint * getParent ()
Constraint * getRoot ()
Static Public Member Functions
static bool classof (const Constraint *C)
Additional Inherited Members
Public Types inherited from vara::feature::Constraint
enum ConstraintKind {
ConstraintKind::CK_ADDITION, ConstraintKind::CK_AND, ConstraintKind::CK_BINARY, ConstraintKind::CK_DIVISION,
ConstraintKind::CK_EQUAL, ConstraintKind::CK_EQUIVALENCE, ConstraintKind::CK_EXCLUDES, ConstraintKind::CK_FEATURE,
ConstraintKind::CK_GREATER, ConstraintKind::CK_GREATER_EQUAL, ConstraintKind::CK_IMPLIES, ConstraintKind::CK_INTEGER,
ConstraintKind::CK_LESS, ConstraintKind::CK_LESS_EQUAL, ConstraintKind::CK_MULTIPLICATION, ConstraintKind::CK_NEG,
ConstraintKind::CK_NOT, ConstraintKind::CK_NOT_EQUAL, ConstraintKind::CK_OR, ConstraintKind::CK_PRIMARY,
ConstraintKind::CK_SUBTRACTION, ConstraintKind::CK_UNARY, ConstraintKind::CK_XOR
}
Protected Attributes inherited from vara::feature::BinaryConstraint
std::unique_ptr< Constraint > LeftOperand
std::unique_ptr< Constraint > RightOperand
Detailed Description
Definition at line 431 of file Constraint.h.
Constructor & Destructor Documentation
GreaterConstraint()
vara::feature::GreaterConstraint::GreaterConstraint (std::unique_ptr< Constraint > LeftOperand, std::unique_ptr< Constraint > RightOperand) inline
Definition at line 433 of file Constraint.h.
Member Function Documentation
classof()
static bool vara::feature::GreaterConstraint::classof (const Constraint * C) inline static
Definition at line 453 of file Constraint.h.
References vara::feature::Constraint::CK_GREATER, and vara::feature::Constraint::getKind().
clone()
std::unique_ptr<Constraint> vara::feature::GreaterConstraint::clone () inline override virtual
Recursively clones constraint tree.
If this tree contains special nodes (like PrimaryFeatureConstraint) those may need to be updated afterwards.
Returns
root of cloned constraint tree
Implements vara::feature::Constraint.
Definition at line 438 of file Constraint.h.
References vara::feature::BinaryConstraint::getLeftOperand(), and vara::feature::BinaryConstraint::getRightOperand().
toHTML()
std::string vara::feature::GreaterConstraint::toHTML () const inline override virtual
Reimplemented from vara::feature::Constraint.
Definition at line 448 of file Constraint.h.
References vara::feature::BinaryConstraint::LeftOperand, and vara::feature::BinaryConstraint::RightOperand.
toString()
std::string vara::feature::GreaterConstraint::toString () const inline override virtual
Implements vara::feature::Constraint.
Definition at line 443 of file Constraint.h.
References vara::feature::BinaryConstraint::LeftOperand, and vara::feature::BinaryConstraint::RightOperand.
The documentation for this class was generated from the following file:
include/vara/Feature/Constraint.h