vara-feature: vara::feature::MultiplicationConstraint Class Reference
vara::feature::MultiplicationConstraint Class Reference
#include "vara/Feature/Constraint.h"
Public Member Functions
MultiplicationConstraint (std::unique_ptr< Constraint > LeftOperand, std::unique_ptr< Constraint > RightOperand)
std::unique_ptr< Constraint > clone () override
Recursively clones constraint tree.
std::string toString () const override
Public Member Functions inherited from vara::feature::BinaryConstraint
BinaryConstraint (ConstraintKind Kind, std::unique_ptr< Constraint > LeftOperand, std::unique_ptr< Constraint > RightOperand)
Constraint * getLeftOperand () const
Constraint * getRightOperand () const
void accept (ConstraintVisitor &V) override
Public Member Functions inherited from vara::feature::Constraint
Constraint (ConstraintKind Kind)
Constraint (const Constraint &)=delete
Constraint & operator= (Constraint &)=delete
Constraint (Constraint &&)=delete
Constraint & operator= (Constraint &&)=delete
virtual ~Constraint ()=default
ConstraintKind getKind () const
void setParent (Constraint *P)
Constraint * getParent ()
Constraint * getRoot ()
virtual std::string toHTML () const
Static Public Member Functions
static bool classof (const Constraint *C)
Additional Inherited Members
Public Types inherited from vara::feature::Constraint
enum ConstraintKind {
ConstraintKind::CK_BINARY, ConstraintKind::CK_OR, ConstraintKind::CK_XOR, ConstraintKind::CK_AND,
ConstraintKind::CK_EQUALS, ConstraintKind::CK_IMPLIES, ConstraintKind::CK_EXCLUDES, ConstraintKind::CK_EQUIVALENCE,
ConstraintKind::CK_ADDITION, ConstraintKind::CK_SUBTRACTION, ConstraintKind::CK_MULTIPLICATION, ConstraintKind::CK_DIVISION,
ConstraintKind::CK_LESS, ConstraintKind::CK_GREATER, ConstraintKind::CK_LESSEQUAL, ConstraintKind::CK_GREATEREQUAL,
ConstraintKind::CK_UNARY, ConstraintKind::CK_NOT, ConstraintKind::CK_NEG, ConstraintKind::CK_PRIMARY,
ConstraintKind::CK_INTEGER, ConstraintKind::CK_FEATURE
}
Protected Attributes inherited from vara::feature::BinaryConstraint
std::unique_ptr< Constraint > LeftOperand
std::unique_ptr< Constraint > RightOperand
Detailed Description
Definition at line 336 of file Constraint.h.
Constructor & Destructor Documentation
MultiplicationConstraint()
vara::feature::MultiplicationConstraint::MultiplicationConstraint (std::unique_ptr< Constraint > LeftOperand, std::unique_ptr< Constraint > RightOperand) inline
Definition at line 339 of file Constraint.h.
Member Function Documentation
classof()
static bool vara::feature::MultiplicationConstraint::classof (const Constraint * C) inline static
Definition at line 354 of file Constraint.h.
References vara::feature::Constraint::CK_MULTIPLICATION, and vara::feature::Constraint::getKind().
clone()
std::unique_ptr<Constraint> vara::feature::MultiplicationConstraint::clone () inline override virtual
Recursively clones constraint tree.
If this tree contains special nodes (like PrimaryFeatureConstraint) those may need to be updated afterwards.
Returns
root of cloned constraint tree
Implements vara::feature::Constraint.
Definition at line 344 of file Constraint.h.
References vara::feature::BinaryConstraint::getLeftOperand(), and vara::feature::BinaryConstraint::getRightOperand().
toString()
std::string vara::feature::MultiplicationConstraint::toString () const inline override virtual
Implements vara::feature::Constraint.
Definition at line 349 of file Constraint.h.
References vara::feature::BinaryConstraint::LeftOperand, and vara::feature::BinaryConstraint::RightOperand.
The documentation for this class was generated from the following file:
include/vara/Feature/Constraint.h