vara-feature: vara::feature::detail::SetRoot Class Reference
vara::feature::detail::SetRoot Class Reference
#include "vara/Feature/FeatureModelTransaction.h"
Public Member Functions
Result< FTErrorCode > exec (FeatureModel &FM) override
Execute the modification on the given FeatureModel.
Result< FTErrorCode, RootFeature * > operator() (FeatureModel &FM)
Public Member Functions inherited from vara::feature::detail::FeatureModelModification
virtual ~FeatureModelModification ()=default
Friends
class FeatureModelModification
Additional Inherited Members
Static Protected Member Functions inherited from vara::feature::detail::FeatureModelModification
static void setParent (FeatureTreeNode &F, FeatureTreeNode &Parent)
Set the parent of a Feature.
static void removeParent (FeatureTreeNode &F)
Remove the parent of a Feature.
static void addEdge (FeatureTreeNode &F, FeatureTreeNode &Child)
Add a Feature Child to F.
static void removeEdge (FeatureTreeNode &F, FeatureTreeNode &Child)
Remove Feature Child from F.
static void addConstraint (Feature &F, PrimaryFeatureConstraint &Constraint)
static void addLocation (Feature &F, FeatureSourceRange FSR)
static void removeLocation (Feature &F, const FeatureSourceRange &FSR)
static void setFeature (PrimaryFeatureConstraint &Constraint, Feature &F)
static Feature * addFeature (FeatureModel &FM, std::unique_ptr< Feature > NewFeature)
Adds a new Feature to the FeatureModel.
static Relationship * addRelationship (FeatureModel &FM, std::unique_ptr< Relationship > NewRelationship)
static void removeRelationship (FeatureModel &FM, Relationship *R)
static Constraint * addConstraint (FeatureModel &FM, std::unique_ptr< Constraint > Constraint)
static void setName (FeatureModel &FM, std::string NewName)
static void setCommit (FeatureModel &FM, std::string NewCommit)
static void setPath (FeatureModel &FM, fs::path NewPath)
static RootFeature * setRoot (FeatureModel &FM, RootFeature &NewRoot)
static void removeFeature (FeatureModel &FM, Feature &F)
Remove Feature from a FeatureModel.
template<typename ModTy , typename... ArgTys>
static ModTy makeModification (ArgTys &&...Args)
template<typename ModTy , typename... ArgTys>
static std::unique_ptr< ModTy > makeUniqueModification (ArgTys &&...Args)
Detailed Description
Definition at line 692 of file FeatureModelTransaction.h.
Member Function Documentation
exec()
Result<FTErrorCode> vara::feature::detail::SetRoot::exec (FeatureModel & FM) inline override virtual
Execute the modification on the given FeatureModel.
Implements vara::feature::detail::FeatureModelModification.
Definition at line 696 of file FeatureModelTransaction.h.
operator()()
Result<FTErrorCode, RootFeature *> vara::feature::detail::SetRoot::operator() (FeatureModel & FM) inline
Definition at line 703 of file FeatureModelTransaction.h.
References vara::feature::detail::FeatureModelModification::addEdge(), vara::feature::detail::FeatureModelModification::addFeature(), vara::feature::ALREADY_PRESENT, vara::feature::FeatureTreeNode::children(), vara::feature::Feature::getName(), vara::feature::FeatureModel::getRoot(), vara::feature::detail::FeatureModelModification::removeEdge(), vara::feature::detail::FeatureModelModification::removeFeature(), vara::feature::detail::FeatureModelModification::setParent(), and vara::feature::detail::FeatureModelModification::setRoot().
Friends And Related Function Documentation
FeatureModelModification
friend class FeatureModelModification friend
Definition at line 693 of file FeatureModelTransaction.h.
The documentation for this class was generated from the following file:
include/vara/Feature/FeatureModelTransaction.h