vara-feature: vara::feature::detail::FeatureModelCopyTransactionBase Class Reference
vara::feature::detail::FeatureModelCopyTransactionBase Class Reference
#include "vara/Feature/FeatureModelTransaction.h"
Protected Member Functions
FeatureModelCopyTransactionBase (FeatureModel &FM)
Result< FTErrorCode, std::unique_ptr< FeatureModel > > commitImpl ()
void abortImpl ()
bool isUncommitted () const
Result< FTErrorCode, Feature * > addFeatureImpl (std::unique_ptr< Feature > NewFeature, Feature *Parent)
void removeFeatureImpl (FeatureVariantTy &F, bool Recursive=false)
Result< FTErrorCode, Relationship * > addRelationshipImpl (Relationship::RelationshipKind Kind, const FeatureVariantTy &Parent)
void removeRelationshipImpl (const FeatureVariantTy &F)
void addLocationImpl (const FeatureVariantTy &F, FeatureSourceRange FSR)
void removeLocationImpl (const FeatureVariantTy &F, FeatureSourceRange &FSR)
Result< FTErrorCode, Constraint * > addConstraintImpl (std::unique_ptr< Constraint > NewConstraint)
void setNameImpl (std::string Name)
void setCommitImpl (std::string Commit)
void setPathImpl (fs::path Path)
Result< FTErrorCode, RootFeature * > setRootImpl (std::unique_ptr< RootFeature > Root)
Static Protected Member Functions
static void addChildImpl (const FeatureTreeNodeVariantTy &Parent, const FeatureTreeNodeVariantTy &Child)
Detailed Description
Definition at line 778 of file FeatureModelTransaction.h.
Constructor & Destructor Documentation
FeatureModelCopyTransactionBase()
vara::feature::detail::FeatureModelCopyTransactionBase::FeatureModelCopyTransactionBase (FeatureModel & FM) inline protected
Definition at line 780 of file FeatureModelTransaction.h.
Member Function Documentation
abortImpl()
void vara::feature::detail::FeatureModelCopyTransactionBase::abortImpl () inline protected
Definition at line 791 of file FeatureModelTransaction.h.
Referenced by commitImpl().
addChildImpl()
static void vara::feature::detail::FeatureModelCopyTransactionBase::addChildImpl (const FeatureTreeNodeVariantTy & Parent, const FeatureTreeNodeVariantTy & Child) inline static protected
Definition at line 931 of file FeatureModelTransaction.h.
addConstraintImpl()
Result<FTErrorCode, Constraint *> vara::feature::detail::FeatureModelCopyTransactionBase::addConstraintImpl (std::unique_ptr< Constraint > NewConstraint) inline protected
Definition at line 893 of file FeatureModelTransaction.h.
References vara::feature::ERROR.
addFeatureImpl()
Result<FTErrorCode, Feature *> vara::feature::detail::FeatureModelCopyTransactionBase::addFeatureImpl (std::unique_ptr< Feature > NewFeature, Feature * Parent) inline protected
Definition at line 804 of file FeatureModelTransaction.h.
References vara::feature::ERROR.
addLocationImpl()
void vara::feature::detail::FeatureModelCopyTransactionBase::addLocationImpl (const FeatureVariantTy & F, FeatureSourceRange FSR) inline protected
Definition at line 864 of file FeatureModelTransaction.h.
addRelationshipImpl()
Result<FTErrorCode, Relationship *> vara::feature::detail::FeatureModelCopyTransactionBase::addRelationshipImpl (Relationship::RelationshipKind Kind, const FeatureVariantTy & Parent) inline protected
Definition at line 835 of file FeatureModelTransaction.h.
References vara::feature::ERROR.
commitImpl()
Result<FTErrorCode, std::unique_ptr<FeatureModel> > vara::feature::detail::FeatureModelCopyTransactionBase::commitImpl () inline protected
Definition at line 783 of file FeatureModelTransaction.h.
References vara::feature::ABORTED, abortImpl(), vara::feature::FeatureModelConsistencyChecker< Rules >::isFeatureModelValid(), and isUncommitted().
isUncommitted()
bool vara::feature::detail::FeatureModelCopyTransactionBase::isUncommitted () const inline protected
Definition at line 796 of file FeatureModelTransaction.h.
Referenced by commitImpl().
removeFeatureImpl()
void vara::feature::detail::FeatureModelCopyTransactionBase::removeFeatureImpl (FeatureVariantTy & F, bool Recursive = false) inline protected
Definition at line 820 of file FeatureModelTransaction.h.
removeLocationImpl()
void vara::feature::detail::FeatureModelCopyTransactionBase::removeLocationImpl (const FeatureVariantTy & F, FeatureSourceRange & FSR) inline protected
Definition at line 878 of file FeatureModelTransaction.h.
removeRelationshipImpl()
void vara::feature::detail::FeatureModelCopyTransactionBase::removeRelationshipImpl (const FeatureVariantTy & F) inline protected
Definition at line 851 of file FeatureModelTransaction.h.
setCommitImpl()
void vara::feature::detail::FeatureModelCopyTransactionBase::setCommitImpl (std::string Commit) inline protected
Definition at line 908 of file FeatureModelTransaction.h.
setNameImpl()
void vara::feature::detail::FeatureModelCopyTransactionBase::setNameImpl (std::string Name) inline protected
Definition at line 902 of file FeatureModelTransaction.h.
setPathImpl()
void vara::feature::detail::FeatureModelCopyTransactionBase::setPathImpl (fs::path Path) inline protected
Definition at line 915 of file FeatureModelTransaction.h.
setRootImpl()
Result<FTErrorCode, RootFeature *> vara::feature::detail::FeatureModelCopyTransactionBase::setRootImpl (std::unique_ptr< RootFeature > Root) inline protected
Definition at line 922 of file FeatureModelTransaction.h.
References vara::feature::ERROR.
The documentation for this class was generated from the following file:
include/vara/Feature/FeatureModelTransaction.h