vara-feature: vara::feature::FeatureModelTransaction< CopyMode > Class Template Reference
vara::feature::FeatureModelTransaction< CopyMode > Class Template Reference
#include "vara/Feature/FeatureModelTransaction.h"
Public Member Functions
FeatureModelTransaction (const FeatureModelTransaction &)=delete
FeatureModelTransaction & operator= (const FeatureModelTransaction &)=delete
FeatureModelTransaction (FeatureModelTransaction &&) noexcept=default
FeatureModelTransaction & operator= (FeatureModelTransaction &&) noexcept=default
~FeatureModelTransaction ()
decltype(auto) commit ()
Commit and finalize the FeatureModelTransaction.
void abort ()
Abort the current Transaction, throwing away all changes.
decltype(auto) addFeature (std::unique_ptr< Feature > NewFeature, Feature *Parent=nullptr)
Add a Feature to the FeatureModel.
void removeFeature (detail::FeatureVariantTy &F, bool Recursive=false)
decltype(auto) addRelationship (Relationship::RelationshipKind Kind, const detail::FeatureVariantTy &Parent)
void removeRelationship (const detail::FeatureVariantTy &F)
decltype(auto) addLocation (const detail::FeatureVariantTy &F, FeatureSourceRange FSR)
void removeLocation (detail::FeatureVariantTy &F, FeatureSourceRange FSR)
decltype(auto) addConstraint (std::unique_ptr< Constraint > Constraint)
void setName (std::string Name)
void setCommit (std::string Commit)
void setPath (fs::path Path)
decltype(auto) setRoot (std::unique_ptr< RootFeature > Root)
decltype(auto) addChild (const detail::FeatureTreeNodeVariantTy &Parent, const detail::FeatureTreeNodeVariantTy &Child)
Static Public Member Functions
static FeatureModelTransaction openTransaction (FeatureModel &FM)
Opens a new Transaction for the given FeatureModel.
Detailed Description
template<typename CopyMode>
class vara::feature::FeatureModelTransaction< CopyMode >
Definition at line 35 of file FeatureModelTransaction.h.
Constructor & Destructor Documentation
FeatureModelTransaction() [1/2]
template<typename CopyMode > vara::feature::FeatureModelTransaction< CopyMode >::FeatureModelTransaction (const FeatureModelTransaction< CopyMode > &) delete
Referenced by vara::feature::FeatureModelTransaction< vara::feature::detail::ModifyTransactionMode >::openTransaction().
FeatureModelTransaction() [2/2]
template<typename CopyMode > vara::feature::FeatureModelTransaction< CopyMode >::FeatureModelTransaction (FeatureModelTransaction< CopyMode > &&) default noexcept
~FeatureModelTransaction()
template<typename CopyMode > vara::feature::FeatureModelTransaction< CopyMode >::~FeatureModelTransaction () inline
Definition at line 63 of file FeatureModelTransaction.h.
Member Function Documentation
abort()
template<typename CopyMode > void vara::feature::FeatureModelTransaction< CopyMode >::abort () inline
Abort the current Transaction, throwing away all changes.
Definition at line 87 of file FeatureModelTransaction.h.
addChild()
template<typename CopyMode > decltype(auto) vara::feature::FeatureModelTransaction< CopyMode >::addChild (const detail::FeatureTreeNodeVariantTy & Parent, const detail::FeatureTreeNodeVariantTy & Child) inline
Definition at line 157 of file FeatureModelTransaction.h.
addConstraint()
template<typename CopyMode > decltype(auto) vara::feature::FeatureModelTransaction< CopyMode >::addConstraint (std::unique_ptr< Constraint > Constraint) inline
Definition at line 133 of file FeatureModelTransaction.h.
addFeature()
template<typename CopyMode > decltype(auto) vara::feature::FeatureModelTransaction< CopyMode >::addFeature (std::unique_ptr< Feature > NewFeature, Feature * Parent = nullptr) inline
Add a Feature to the FeatureModel.
Returns
a pointer to the inserted Feature in CopyMode, otherwise, nothing.
Definition at line 93 of file FeatureModelTransaction.h.
Referenced by vara::feature::mergeSubtree().
addLocation()
template<typename CopyMode > decltype(auto) vara::feature::FeatureModelTransaction< CopyMode >::addLocation (const detail::FeatureVariantTy & F, FeatureSourceRange FSR) inline
Definition at line 120 of file FeatureModelTransaction.h.
Referenced by vara::feature::mergeSubtree().
addRelationship()
template<typename CopyMode > decltype(auto) vara::feature::FeatureModelTransaction< CopyMode >::addRelationship (Relationship::RelationshipKind Kind, const detail::FeatureVariantTy & Parent) inline
Definition at line 107 of file FeatureModelTransaction.h.
commit()
template<typename CopyMode > decltype(auto) vara::feature::FeatureModelTransaction< CopyMode >::commit () inline
Commit and finalize the FeatureModelTransaction.
In CopyMode a new FeatureModel is returned. In ModifyMode the specified changes are applied to the underlying FeatureModel.
Returns
a FeatureModel or nothing
Definition at line 84 of file FeatureModelTransaction.h.
Referenced by vara::feature::FeatureModelTransaction< vara::feature::detail::ModifyTransactionMode >::~FeatureModelTransaction().
openTransaction()
template<typename CopyMode > static FeatureModelTransaction vara::feature::FeatureModelTransaction< CopyMode >::openTransaction (FeatureModel & FM) inline static
Opens a new Transaction for the given FeatureModel.
The Transaction enables the user to modify the underlying FeatureModel via a specific API, preserving the correctness of the FeatureModel.
Definition at line 50 of file FeatureModelTransaction.h.
Referenced by vara::feature::addFeature(), vara::feature::addFeatures(), vara::feature::addRelationship(), vara::feature::mergeFeatureModels(), vara::feature::removeFeature(), vara::feature::removeFeatures(), vara::feature::removeRelationship(), and vara::feature::setCommit().
operator=() [1/2]
template<typename CopyMode > FeatureModelTransaction& vara::feature::FeatureModelTransaction< CopyMode >::operator= (const FeatureModelTransaction< CopyMode > &) delete
operator=() [2/2]
template<typename CopyMode > FeatureModelTransaction& vara::feature::FeatureModelTransaction< CopyMode >::operator= (FeatureModelTransaction< CopyMode > &&) default noexcept
removeFeature()
template<typename CopyMode > void vara::feature::FeatureModelTransaction< CopyMode >::removeFeature (detail::FeatureVariantTy & F, bool Recursive = false) inline
Definition at line 102 of file FeatureModelTransaction.h.
removeLocation()
template<typename CopyMode > void vara::feature::FeatureModelTransaction< CopyMode >::removeLocation (detail::FeatureVariantTy & F, FeatureSourceRange FSR) inline
Definition at line 129 of file FeatureModelTransaction.h.
removeRelationship()
template<typename CopyMode > void vara::feature::FeatureModelTransaction< CopyMode >::removeRelationship (const detail::FeatureVariantTy & F) inline
Definition at line 116 of file FeatureModelTransaction.h.
setCommit()
template<typename CopyMode > void vara::feature::FeatureModelTransaction< CopyMode >::setCommit (std::string Commit) inline
Definition at line 143 of file FeatureModelTransaction.h.
setName()
template<typename CopyMode > void vara::feature::FeatureModelTransaction< CopyMode >::setName (std::string Name) inline
Definition at line 141 of file FeatureModelTransaction.h.
setPath()
template<typename CopyMode > void vara::feature::FeatureModelTransaction< CopyMode >::setPath (fs::path Path) inline
Definition at line 147 of file FeatureModelTransaction.h.
setRoot()
template<typename CopyMode > decltype(auto) vara::feature::FeatureModelTransaction< CopyMode >::setRoot (std::unique_ptr< RootFeature > Root) inline
Definition at line 149 of file FeatureModelTransaction.h.
The documentation for this class was generated from the following file:
include/vara/Feature/FeatureModelTransaction.h