vara-feature: vara::solver::Z3SolverConstraintVisitor Class Reference
vara::solver::Z3SolverConstraintVisitor Class Reference
This class is a visitor to convert the constraints from the feature model into constraints for Z3.
#include "vara/Solver/Z3Solver.h"
Public Member Functions
Z3SolverConstraintVisitor (Z3Solver *S, bool MixedConstraint=false)
Constructs a new solver constraint visitor by using the reference to the solver.
bool addConstraint (vara::feature::Constraint *C, bool NegateExpr=false, bool RequireAll=true)
This method adds the constraint after visiting the constraint and constructing it while visiting.
bool visit (vara::feature::BinaryConstraint *C) override
Visits the binary constraint.
bool visit (vara::feature::UnaryConstraint *C) override
Visits the unary constraints.
bool visit (vara::feature::PrimaryFeatureConstraint *C) override
Visits the feature in the constraint.
bool visit (feature::PrimaryIntegerConstraint *C) override
Visits the feature in the integer constraints.
Public Member Functions inherited from vara::feature::ConstraintVisitor
virtual ~ConstraintVisitor ()=default
Detailed Description
This class is a visitor to convert the constraints from the feature model into constraints for Z3.
Definition at line 102 of file Z3Solver.h.
Constructor & Destructor Documentation
Z3SolverConstraintVisitor()
vara::solver::Z3SolverConstraintVisitor::Z3SolverConstraintVisitor (Z3Solver * S, bool MixedConstraint = false) inline
Constructs a new solver constraint visitor by using the reference to the solver.
This reference is needed to retrieve the context and reuse it in the visitor.
Parameters
S The Z3Solver instance that uses this visitor.
MixedConstraint whether the visitor is applied on mixed constraints or not.
Definition at line 111 of file Z3Solver.h.
Member Function Documentation
addConstraint()
bool vara::solver::Z3SolverConstraintVisitor::addConstraint (vara::feature::Constraint * C, bool NegateExpr = false, bool RequireAll = true)
This method adds the constraint after visiting the constraint and constructing it while visiting.
Parameters
C The constraint to visit
NegateExpr Whether the expression should be evaluated as is or negated
RequireAll Whether all binary features have to be selected in order to evaluate the mixed constraint or not
Returns
true if adding the constraint was successfull; false otherwise.
Definition at line 270 of file Z3Solver.cpp.
References vara::feature::Constraint::accept().
Referenced by vara::solver::Z3Solver::addConstraint(), and vara::solver::Z3Solver::addMixedConstraint().
visit() [1/4]
bool vara::solver::Z3SolverConstraintVisitor::visit (feature::PrimaryIntegerConstraint * C) override virtual
Visits the feature in the integer constraints.
This method creates the according z3 constant.
Parameters
C the integer constraint
Returns
true if adding the constraint was successfull; false otherwise.
Reimplemented from vara::feature::ConstraintVisitor.
Definition at line 391 of file Z3Solver.cpp.
References vara::feature::PrimaryIntegerConstraint::getValue().
visit() [2/4]
bool vara::solver::Z3SolverConstraintVisitor::visit (vara::feature::BinaryConstraint * C) override virtual
Visits the binary constraint.
Thereby, it constructs the z3 constraint by first executing the first part of the binary operator and afterwards the second (right) part.
Parameters
C the binary constraint to be converted
Returns
true if adding the constraint was successfull; false otherwise.
Reimplemented from vara::feature::ConstraintVisitor.
Definition at line 287 of file Z3Solver.cpp.
References vara::feature::Constraint::accept(), vara::feature::Constraint::CK_ADDITION, vara::feature::Constraint::CK_AND, vara::feature::Constraint::CK_DIVISION, vara::feature::Constraint::CK_EQUAL, vara::feature::Constraint::CK_EQUIVALENCE, vara::feature::Constraint::CK_EXCLUDES, vara::feature::Constraint::CK_GREATER, vara::feature::Constraint::CK_GREATER_EQUAL, vara::feature::Constraint::CK_IMPLIES, vara::feature::Constraint::CK_LESS, vara::feature::Constraint::CK_LESS_EQUAL, vara::feature::Constraint::CK_MULTIPLICATION, vara::feature::Constraint::CK_NOT_EQUAL, vara::feature::Constraint::CK_OR, vara::feature::Constraint::CK_SUBTRACTION, vara::feature::Constraint::CK_XOR, vara::feature::Constraint::getKind(), vara::feature::BinaryConstraint::getLeftOperand(), and vara::feature::BinaryConstraint::getRightOperand().
visit() [3/4]
bool vara::solver::Z3SolverConstraintVisitor::visit (vara::feature::PrimaryFeatureConstraint * C) override virtual
Visits the feature in the constraint.
This method creates the according z3 constant.
Parameters
C the primary feature
Returns
true if adding the constraint was successfull; false otherwise.
Reimplemented from vara::feature::ConstraintVisitor.
Definition at line 372 of file Z3Solver.cpp.
References vara::feature::Feature::FK_NUMERIC, vara::feature::PrimaryFeatureConstraint::getFeature(), vara::feature::Feature::getKind(), and vara::feature::Feature::getName().
visit() [4/4]
bool vara::solver::Z3SolverConstraintVisitor::visit (vara::feature::UnaryConstraint * C) override virtual
Visits the unary constraints.
Thereby, it visits the operand and creates a new z3 constraint by preceeding it with the according expression.
Parameters
C the unary constraint to visit
Returns
true if adding the constraint was successfull; false otherwise.
Reimplemented from vara::feature::ConstraintVisitor.
Definition at line 355 of file Z3Solver.cpp.
References vara::feature::Constraint::accept(), vara::feature::Constraint::CK_NEG, vara::feature::Constraint::CK_NOT, vara::feature::Constraint::getKind(), and vara::feature::UnaryConstraint::getOperand().
The documentation for this class was generated from the following files:
include/vara/Solver/Z3Solver.h
lib/Solver/Z3Solver.cpp