vara-feature: vara::feature::detail::FeatureModelModification Class Reference
vara::feature::detail::FeatureModelModification Class Reference abstract
#include "vara/Feature/FeatureModelTransaction.h"
Public Member Functions
virtual ~FeatureModelModification ()=default
virtual void exec (FeatureModel &FM)=0
Execute the modification on the given FeatureModel.
Static Protected Member Functions
static void setParent (FeatureTreeNode &F, FeatureTreeNode &Parent)
Set the parent of a Feature.
static void removeParent (FeatureTreeNode &F)
Remove the parent of a Feature.
static void addEdge (FeatureTreeNode &F, FeatureTreeNode &Child)
Add a Feature Child to F.
static void removeEdge (FeatureTreeNode &F, FeatureTreeNode &Child)
Remove Feature Child from F.
static void addConstraint (Feature &F, PrimaryFeatureConstraint &Constraint)
static void addLocation (Feature &F, FeatureSourceRange FSR)
static void removeLocation (Feature &F, const FeatureSourceRange &FSR)
static void setFeature (PrimaryFeatureConstraint &Constraint, Feature &F)
static Feature * addFeature (FeatureModel &FM, std::unique_ptr< Feature > NewFeature)
Adds a new Feature to the FeatureModel.
static Relationship * addRelationship (FeatureModel &FM, std::unique_ptr< Relationship > NewRelationship)
static void removeRelationship (FeatureModel &FM, Relationship *R)
static Constraint * addConstraint (FeatureModel &FM, std::unique_ptr< Constraint > Constraint)
static void setName (FeatureModel &FM, std::string NewName)
static void setCommit (FeatureModel &FM, std::string NewCommit)
static void setPath (FeatureModel &FM, fs::path NewPath)
static RootFeature * setRoot (FeatureModel &FM, RootFeature &NewRoot)
static void removeFeature (FeatureModel &FM, Feature &F)
Remove Feature from a FeatureModel.
template<typename ModTy , typename... ArgTys>
static ModTy make_modification (ArgTys &&...Args)
template<typename ModTy , typename... ArgTys>
static std::unique_ptr< ModTy > make_unique_modification (ArgTys &&...Args)
Friends
class FeatureModelCopyTransactionBase
class FeatureModelModifyTransactionBase
Detailed Description
Definition at line 185 of file FeatureModelTransaction.h.
Constructor & Destructor Documentation
~FeatureModelModification()
virtual vara::feature::detail::FeatureModelModification::~FeatureModelModification () virtual default
Member Function Documentation
addConstraint() [1/2]
static void vara::feature::detail::FeatureModelModification::addConstraint (Feature & F, PrimaryFeatureConstraint & Constraint) inline static protected
Definition at line 214 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::AddConstraintToModel::operator()().
addConstraint() [2/2]
static Constraint* vara::feature::detail::FeatureModelModification::addConstraint (FeatureModel & FM, std::unique_ptr< Constraint > Constraint) inline static protected
Definition at line 251 of file FeatureModelTransaction.h.
addEdge()
static void vara::feature::detail::FeatureModelModification::addEdge (FeatureTreeNode & F, FeatureTreeNode & Child) inline static protected
Add a Feature Child to F.
Definition at line 205 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::AddFeatureToModel::operator()(), vara::feature::detail::AddRelationshipToModel::operator()(), vara::feature::detail::RemoveRelationshipFromModel::operator()(), vara::feature::detail::SetRoot::operator()(), and vara::feature::detail::AddChild::operator()().
addFeature()
static Feature* vara::feature::detail::FeatureModelModification::addFeature (FeatureModel & FM, std::unique_ptr< Feature > NewFeature) inline static protected
Adds a new Feature to the FeatureModel.
Parameters
FM model to add to
NewFeature the Feature to add
Returns
A pointer to the inserted Feature.
Definition at line 236 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::AddFeatureToModel::operator()(), and vara::feature::detail::SetRoot::operator()().
addLocation()
static void vara::feature::detail::FeatureModelModification::addLocation (Feature & F, FeatureSourceRange FSR) inline static protected
Definition at line 218 of file FeatureModelTransaction.h.
References vara::feature::Feature::addLocation().
Referenced by vara::feature::detail::AddLocationToFeature::operator()().
addRelationship()
static Relationship* vara::feature::detail::FeatureModelModification::addRelationship (FeatureModel & FM, std::unique_ptr< Relationship > NewRelationship) inline static protected
Definition at line 242 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::AddRelationshipToModel::operator()().
exec()
virtual void vara::feature::detail::FeatureModelModification::exec (FeatureModel & FM) pure virtual
Execute the modification on the given FeatureModel.
Implemented in vara::feature::detail::AddChild, vara::feature::detail::SetRoot, vara::feature::detail::SetPath, vara::feature::detail::SetCommit, vara::feature::detail::SetName, vara::feature::detail::AddConstraintToModel, vara::feature::detail::RemoveLocationFromFeature, vara::feature::detail::AddLocationToFeature, vara::feature::detail::RemoveRelationshipFromModel, vara::feature::detail::AddRelationshipToModel, vara::feature::detail::RemoveFeatureFromModel, and vara::feature::detail::AddFeatureToModel.
make_modification()
template<typename ModTy , typename... ArgTys> static ModTy vara::feature::detail::FeatureModelModification::make_modification (ArgTys &&... Args) inline static protected
Definition at line 281 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::FeatureModelCopyTransactionBase::removeRelationshipImpl().
make_unique_modification()
template<typename ModTy , typename... ArgTys> static std::unique_ptr<ModTy> vara::feature::detail::FeatureModelModification::make_unique_modification (ArgTys &&... Args) inline static protected
Definition at line 286 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::FeatureModelModifyTransactionBase::addConstraintImpl(), vara::feature::detail::FeatureModelModifyTransactionBase::addLocationImpl(), vara::feature::detail::FeatureModelModifyTransactionBase::addRelationshipImpl(), vara::feature::detail::FeatureModelModifyTransactionBase::removeFeatureImpl(), vara::feature::detail::FeatureModelModifyTransactionBase::removeLocationImpl(), and vara::feature::detail::FeatureModelModifyTransactionBase::removeRelationshipImpl().
removeEdge()
static void vara::feature::detail::FeatureModelModification::removeEdge (FeatureTreeNode & F, FeatureTreeNode & Child) inline static protected
Remove Feature Child from F.
Definition at line 210 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::RemoveFeatureFromModel::operator()(), vara::feature::detail::AddRelationshipToModel::operator()(), vara::feature::detail::RemoveRelationshipFromModel::operator()(), vara::feature::detail::SetRoot::operator()(), and vara::feature::detail::AddChild::operator()().
removeFeature()
static void vara::feature::detail::FeatureModelModification::removeFeature (FeatureModel & FM, Feature & F) inline static protected
Remove Feature from a FeatureModel.
Parameters
FM model to remove from
F the Feature to delete
Definition at line 276 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::RemoveFeatureFromModel::operator()(), and vara::feature::detail::SetRoot::operator()().
removeLocation()
static void vara::feature::detail::FeatureModelModification::removeLocation (Feature & F, const FeatureSourceRange & FSR) inline static protected
Definition at line 222 of file FeatureModelTransaction.h.
References vara::feature::Feature::removeLocation().
Referenced by vara::feature::detail::RemoveLocationFromFeature::operator()().
removeParent()
static void vara::feature::detail::FeatureModelModification::removeParent (FeatureTreeNode & F) inline static protected
Remove the parent of a Feature.
Definition at line 202 of file FeatureModelTransaction.h.
removeRelationship()
static void vara::feature::detail::FeatureModelModification::removeRelationship (FeatureModel & FM, Relationship * R) inline static protected
Definition at line 247 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::RemoveFeatureFromModel::operator()(), and vara::feature::detail::RemoveRelationshipFromModel::operator()().
setCommit()
static void vara::feature::detail::FeatureModelModification::setCommit (FeatureModel & FM, std::string NewCommit) inline static protected
Definition at line 260 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::SetCommit::operator()().
setFeature()
static void vara::feature::detail::FeatureModelModification::setFeature (PrimaryFeatureConstraint & Constraint, Feature & F) inline static protected
Definition at line 226 of file FeatureModelTransaction.h.
setName()
static void vara::feature::detail::FeatureModelModification::setName (FeatureModel & FM, std::string NewName) inline static protected
Definition at line 256 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::SetName::operator()().
setParent()
static void vara::feature::detail::FeatureModelModification::setParent (FeatureTreeNode & F, FeatureTreeNode & Parent) inline static protected
Set the parent of a Feature.
Definition at line 197 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::AddFeatureToModel::operator()(), vara::feature::detail::AddRelationshipToModel::operator()(), vara::feature::detail::RemoveRelationshipFromModel::operator()(), vara::feature::detail::SetRoot::operator()(), and vara::feature::detail::AddChild::operator()().
setPath()
static void vara::feature::detail::FeatureModelModification::setPath (FeatureModel & FM, fs::path NewPath) inline static protected
Definition at line 264 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::SetPath::operator()().
setRoot()
static RootFeature* vara::feature::detail::FeatureModelModification::setRoot (FeatureModel & FM, RootFeature & NewRoot) inline static protected
Definition at line 268 of file FeatureModelTransaction.h.
Referenced by vara::feature::detail::SetRoot::operator()().
Friends And Related Function Documentation
FeatureModelCopyTransactionBase
friend class FeatureModelCopyTransactionBase friend
Definition at line 186 of file FeatureModelTransaction.h.
FeatureModelModifyTransactionBase
friend class FeatureModelModifyTransactionBase friend
Definition at line 187 of file FeatureModelTransaction.h.
The documentation for this class was generated from the following file:
include/vara/Feature/FeatureModelTransaction.h