vara-feature: vara::feature::FeatureTreeNode Class Reference
vara::feature::FeatureTreeNode Class Reference
#include "vara/Feature/FeatureTreeNode.h"
Public Types
enum NodeKind { NodeKind::NK_FEATURE, NodeKind::NK_RELATIONSHIP }
using NodeSetType = typename llvm::SmallSet< FeatureTreeNode *, 3 >
Public Member Functions
FeatureTreeNode (NodeKind Kind)
FeatureTreeNode (FeatureTreeNode &)=delete
FeatureTreeNode & operator= (FeatureTreeNode &)=delete
FeatureTreeNode (FeatureTreeNode &&)=delete
FeatureTreeNode & operator= (FeatureTreeNode &&)=delete
virtual ~FeatureTreeNode ()=default
NodeKind getKind () const
FeatureTreeNode * getParent () const
bool hasEdgeFrom (FeatureTreeNode &N) const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
llvm::iterator_range< iterator > children ()
llvm::iterator_range< const_iterator > children () const
bool hasEdgeTo (const FeatureTreeNode &N) const
template<typename T = FeatureTreeNode>
llvm::SmallSet< T *, 3 > getChildren (int Depth=-1)
Search first (possibly transitive) children of given type in tree structure.
bool isLeaf ()
Checks if a FeatureTreeNode has children or is a leaf.
Protected Member Functions
FeatureTreeNode (NodeKind Kind, FeatureTreeNode *Parent, const llvm::SmallPtrSetImpl< FeatureTreeNode * > &Children)
FeatureTreeNode (NodeKind Kind, FeatureTreeNode *Parent, const std::vector< FeatureTreeNode * > &Children)
Friends
class FeatureModel
class FeatureModelBuilder
class detail::FeatureModelModification
Detailed Description
Definition at line 31 of file FeatureTreeNode.h.
Member Typedef Documentation
NodeSetType
using vara::feature::FeatureTreeNode::NodeSetType = typename llvm::SmallSet<FeatureTreeNode *, 3>
Definition at line 39 of file FeatureTreeNode.h.
Member Enumeration Documentation
NodeKind
enum vara::feature::FeatureTreeNode::NodeKind strong
Enumerator
NK_FEATURE
NK_RELATIONSHIP
Definition at line 37 of file FeatureTreeNode.h.
Constructor & Destructor Documentation
FeatureTreeNode() [1/5]
vara::feature::FeatureTreeNode::FeatureTreeNode (NodeKind Kind) inline
Definition at line 41 of file FeatureTreeNode.h.
FeatureTreeNode() [2/5]
vara::feature::FeatureTreeNode::FeatureTreeNode (FeatureTreeNode &) delete
FeatureTreeNode() [3/5]
vara::feature::FeatureTreeNode::FeatureTreeNode (FeatureTreeNode &&) delete
~FeatureTreeNode()
virtual vara::feature::FeatureTreeNode::~FeatureTreeNode () virtual default
FeatureTreeNode() [4/5]
vara::feature::FeatureTreeNode::FeatureTreeNode (NodeKind Kind, FeatureTreeNode * Parent, const llvm::SmallPtrSetImpl< FeatureTreeNode * > & Children) inline protected
Definition at line 103 of file FeatureTreeNode.h.
FeatureTreeNode() [5/5]
vara::feature::FeatureTreeNode::FeatureTreeNode (NodeKind Kind, FeatureTreeNode * Parent, const std::vector< FeatureTreeNode * > & Children) inline protected
Definition at line 109 of file FeatureTreeNode.h.
Member Function Documentation
begin() [1/2]
iterator vara::feature::FeatureTreeNode::begin () inline
Definition at line 62 of file FeatureTreeNode.h.
Referenced by children(), hasEdgeTo(), vara::feature::detail::RemoveFeatureFromModel::operator()(), and vara::feature::detail::RemoveRelationshipFromModel::operator()().
begin() [2/2]
const_iterator vara::feature::FeatureTreeNode::begin () const inline
Definition at line 63 of file FeatureTreeNode.h.
children() [1/2]
llvm::iterator_range<iterator> vara::feature::FeatureTreeNode::children () inline
Definition at line 68 of file FeatureTreeNode.h.
References begin(), and end().
Referenced by isLeaf(), vara::feature::detail::SetRoot::operator()(), and vara::feature::Feature::toString().
children() [2/2]
llvm::iterator_range<const_iterator> vara::feature::FeatureTreeNode::children () const inline
Definition at line 71 of file FeatureTreeNode.h.
References begin(), and end().
end() [1/2]
iterator vara::feature::FeatureTreeNode::end () inline
Definition at line 65 of file FeatureTreeNode.h.
Referenced by children(), and hasEdgeTo().
end() [2/2]
const_iterator vara::feature::FeatureTreeNode::end () const inline
Definition at line 66 of file FeatureTreeNode.h.
getChildren()
template<typename T = FeatureTreeNode> llvm::SmallSet<T *, 3> vara::feature::FeatureTreeNode::getChildren (int Depth = -1) inline
Search first (possibly transitive) children of given type in tree structure.
Template Parameters
Definition at line 90 of file FeatureTreeNode.h.
Referenced by vara::feature::canBeDeletedRecursively(), and vara::feature::mergeSubtree().
getKind()
NodeKind vara::feature::FeatureTreeNode::getKind () const inline
Definition at line 48 of file FeatureTreeNode.h.
Referenced by vara::feature::Relationship::classof(), vara::feature::Feature::classof(), and vara::feature::compareProperties().
getParent()
FeatureTreeNode* vara::feature::FeatureTreeNode::getParent () const inline
Definition at line 53 of file FeatureTreeNode.h.
Referenced by vara::feature::compareProperties(), and vara::feature::Feature::getParentFeature().
hasEdgeFrom()
bool vara::feature::FeatureTreeNode::hasEdgeFrom (FeatureTreeNode & N) const inline
Definition at line 55 of file FeatureTreeNode.h.
hasEdgeTo()
bool vara::feature::FeatureTreeNode::hasEdgeTo (const FeatureTreeNode & N) const inline
Definition at line 75 of file FeatureTreeNode.h.
References begin(), and end().
isLeaf()
bool vara::feature::FeatureTreeNode::isLeaf () inline
Checks if a FeatureTreeNode has children or is a leaf.
Returns
true, if the FeatureTreeNode does not have children, i.e., is a leaf.
Definition at line 100 of file FeatureTreeNode.h.
References children().
Referenced by vara::feature::fvIsLeaf().
operator=() [1/2]
FeatureTreeNode& vara::feature::FeatureTreeNode::operator= (FeatureTreeNode &&) delete
operator=() [2/2]
FeatureTreeNode& vara::feature::FeatureTreeNode::operator= (FeatureTreeNode &) delete
Friends And Related Function Documentation
detail::FeatureModelModification
friend class detail::FeatureModelModification friend
Definition at line 34 of file FeatureTreeNode.h.
FeatureModel
friend class FeatureModel friend
Definition at line 32 of file FeatureTreeNode.h.
FeatureModelBuilder
friend class FeatureModelBuilder friend
Definition at line 33 of file FeatureTreeNode.h.
The documentation for this class was generated from the following file:
include/vara/Feature/FeatureTreeNode.h