vara-feature: vara::feature::FeatureModel Class Reference
vara::feature::FeatureModel Class Reference
Tree like representation of features and dependencies.
#include "vara/Feature/FeatureModel.h"
Classes
class BooleanConstraint
class DFSIterator
class FeatureMapIterator
class MixedConstraint
class NonBooleanConstraint
Public Types
using FeatureMapTy = llvm::StringMap< std::unique_ptr< Feature > >
using RelationshipContainerTy = std::vector< std::unique_ptr< Relationship > >
using const_ordered_feature_iterator = DFSIterator
using const_unordered_feature_iterator = FeatureMapIterator
using BooleanConstraintContainerTy = std::vector< std::unique_ptr< BooleanConstraint > >
using const_boolean_constraint_iterator = UniqueIterator< const BooleanConstraintContainerTy >
using NonBooleanConstraintContainerTy = std::vector< std::unique_ptr< NonBooleanConstraint > >
using const_non_boolean_constraint_iterator = UniqueIterator< const NonBooleanConstraintContainerTy >
using MixedConstraintContainerTy = std::vector< std::unique_ptr< MixedConstraint > >
using const_mixed_constraint_iterator = UniqueIterator< const MixedConstraintContainerTy >
using const_relationship_iterator = typename RelationshipContainerTy::const_iterator
Public Member Functions
FeatureModel (std::string Name="FeatureModel", std::unique_ptr< RootFeature > Root=std::make_unique< RootFeature >("root"), fs::path Path="", std::string Commit="")
unsigned int size () const
llvm::StringRef getName () const
fs::path getPath () const
llvm::StringRef getCommit () const
RootFeature * getRoot () const
Feature * getFeature (llvm::StringRef F) const
const_ordered_feature_iterator begin () const
const_ordered_feature_iterator end () const
llvm::iterator_range< const_ordered_feature_iterator > features () const
llvm::iterator_range< const_unordered_feature_iterator > unorderedFeatures () const
llvm::iterator_range< const_boolean_constraint_iterator > booleanConstraints () const
llvm::iterator_range< const_non_boolean_constraint_iterator > nonBooleanConstraints () const
llvm::iterator_range< const_mixed_constraint_iterator > mixedConstraints () const
llvm::iterator_range< const_relationship_iterator > relationships () const
void view ()
std::unique_ptr< FeatureModel > clone () const
Create deep clone of whole data structure.
LLVM_DUMP_METHOD void dump () const
Friends
class FeatureModelBuilder
class detail::FeatureModelModification
Detailed Description
Tree like representation of features and dependencies.
Definition at line 31 of file FeatureModel.h.
Member Typedef Documentation
BooleanConstraintContainerTy
using vara::feature::FeatureModel::BooleanConstraintContainerTy = std::vector<std::unique_ptr<BooleanConstraint> >
Definition at line 265 of file FeatureModel.h.
const_boolean_constraint_iterator
using vara::feature::FeatureModel::const_boolean_constraint_iterator = UniqueIterator<const BooleanConstraintContainerTy>
Definition at line 267 of file FeatureModel.h.
const_mixed_constraint_iterator
using vara::feature::FeatureModel::const_mixed_constraint_iterator = UniqueIterator<const MixedConstraintContainerTy>
Definition at line 319 of file FeatureModel.h.
const_non_boolean_constraint_iterator
using vara::feature::FeatureModel::const_non_boolean_constraint_iterator = UniqueIterator<const NonBooleanConstraintContainerTy>
Definition at line 285 of file FeatureModel.h.
const_ordered_feature_iterator
using vara::feature::FeatureModel::const_ordered_feature_iterator = DFSIterator
Definition at line 161 of file FeatureModel.h.
const_relationship_iterator
using vara::feature::FeatureModel::const_relationship_iterator = typename RelationshipContainerTy::const_iterator
Definition at line 332 of file FeatureModel.h.
const_unordered_feature_iterator
using vara::feature::FeatureModel::const_unordered_feature_iterator = FeatureMapIterator
Definition at line 225 of file FeatureModel.h.
FeatureMapTy
using vara::feature::FeatureModel::FeatureMapTy = llvm::StringMap<std::unique_ptr<Feature> >
Definition at line 37 of file FeatureModel.h.
MixedConstraintContainerTy
using vara::feature::FeatureModel::MixedConstraintContainerTy = std::vector<std::unique_ptr<MixedConstraint> >
Definition at line 317 of file FeatureModel.h.
NonBooleanConstraintContainerTy
using vara::feature::FeatureModel::NonBooleanConstraintContainerTy = std::vector<std::unique_ptr<NonBooleanConstraint> >
Definition at line 283 of file FeatureModel.h.
RelationshipContainerTy
using vara::feature::FeatureModel::RelationshipContainerTy = std::vector<std::unique_ptr<Relationship> >
Definition at line 38 of file FeatureModel.h.
Constructor & Destructor Documentation
FeatureModel()
vara::feature::FeatureModel::FeatureModel (std::string Name = "FeatureModel", std::unique_ptr< RootFeature > Root = std::make_unique<RootFeature>("root"), fs::path Path = "", std::string Commit = "") inline
Definition at line 40 of file FeatureModel.h.
References vara::feature::addFeature().
Member Function Documentation
begin()
const_ordered_feature_iterator vara::feature::FeatureModel::begin () const inline
Definition at line 163 of file FeatureModel.h.
Referenced by vara::feature::removeFeatures().
booleanConstraints()
llvm::iterator_range<const_boolean_constraint_iterator> vara::feature::FeatureModel::booleanConstraints () const inline
Definition at line 270 of file FeatureModel.h.
Referenced by clone().
clone()
std::unique_ptr< FeatureModel > vara::feature::FeatureModel::clone () const
Create deep clone of whole data structure.
Returns
new FeatureModel
Definition at line 44 of file FeatureModel.cpp.
References vara::feature::FeatureModelBuilder::addConstraint(), vara::feature::FeatureModelBuilder::addEdge(), booleanConstraints(), vara::feature::FeatureModelBuilder::buildFeatureModel(), vara::feature::FeatureModelBuilder::emplaceRelationship(), vara::feature::Feature::FK_BINARY, vara::feature::Feature::FK_NUMERIC, vara::feature::Feature::FK_ROOT, vara::feature::Feature::FK_UNKNOWN, getCommit(), getName(), getPath(), vara::feature::FeatureModelBuilder::makeFeature(), vara::feature::FeatureModelBuilder::makeRoot(), mixedConstraints(), nonBooleanConstraints(), vara::feature::FeatureModelBuilder::setCommit(), vara::feature::FeatureModelBuilder::setPath(), and vara::feature::FeatureModelBuilder::setVmName().
dump()
void vara::feature::FeatureModel::dump () const
Definition at line 15 of file FeatureModel.cpp.
References vara::feature::Feature::dump().
end()
const_ordered_feature_iterator vara::feature::FeatureModel::end () const inline
Definition at line 164 of file FeatureModel.h.
features()
llvm::iterator_range<const_ordered_feature_iterator> vara::feature::FeatureModel::features () const inline
Definition at line 169 of file FeatureModel.h.
Referenced by vara::sampling::SampleSetParser::readConfigurations(), and vara::sampling::SampleSetWriter::writeConfigurations().
getCommit()
llvm::StringRef vara::feature::FeatureModel::getCommit () const inline
Definition at line 55 of file FeatureModel.h.
Referenced by clone().
getFeature()
Feature* vara::feature::FeatureModel::getFeature (llvm::StringRef F) const inline
Definition at line 62 of file FeatureModel.h.
Referenced by vara::feature::getActualFeature(), vara::feature::mergeSubtree(), vara::feature::detail::RemoveFeatureFromModel::operator()(), vara::feature::detail::AddRelationshipToModel::operator()(), vara::feature::detail::RemoveRelationshipFromModel::operator()(), vara::feature::detail::AddLocationToFeature::operator()(), vara::feature::detail::RemoveLocationFromFeature::operator()(), and vara::feature::detail::AddChild::operator()().
getName()
llvm::StringRef vara::feature::FeatureModel::getName () const inline
Definition at line 51 of file FeatureModel.h.
Referenced by clone().
getPath()
fs::path vara::feature::FeatureModel::getPath () const inline
Definition at line 53 of file FeatureModel.h.
Referenced by clone().
getRoot()
RootFeature* vara::feature::FeatureModel::getRoot () const inline
Definition at line 60 of file FeatureModel.h.
Referenced by vara::feature::ExactlyOneRootNode::check(), vara::feature::mergeFeatureModels(), vara::feature::detail::AddFeatureToModel::operator()(), and vara::feature::detail::SetRoot::operator()().
mixedConstraints()
llvm::iterator_range<const_mixed_constraint_iterator> vara::feature::FeatureModel::mixedConstraints () const inline
Definition at line 322 of file FeatureModel.h.
Referenced by clone().
nonBooleanConstraints()
llvm::iterator_range<const_non_boolean_constraint_iterator> vara::feature::FeatureModel::nonBooleanConstraints () const inline
Definition at line 288 of file FeatureModel.h.
Referenced by clone().
relationships()
llvm::iterator_range<const_relationship_iterator> vara::feature::FeatureModel::relationships () const inline
Definition at line 335 of file FeatureModel.h.
size()
unsigned int vara::feature::FeatureModel::size () const inline
Definition at line 49 of file FeatureModel.h.
unorderedFeatures()
llvm::iterator_range<const_unordered_feature_iterator> vara::feature::FeatureModel::unorderedFeatures () const inline
Definition at line 228 of file FeatureModel.h.
Referenced by vara::feature::EveryFeatureRequiresParent::check(), vara::feature::CheckFeatureParentChildRelationShip::check(), and vara::feature::ExactlyOneRootNode::check().
view()
void vara::feature::FeatureModel::view () inline
Definition at line 342 of file FeatureModel.h.
Friends And Related Function Documentation
detail::FeatureModelModification
friend class detail::FeatureModelModification friend
Definition at line 34 of file FeatureModel.h.
FeatureModelBuilder
friend class FeatureModelBuilder friend
Definition at line 32 of file FeatureModel.h.
The documentation for this class was generated from the following files:
include/vara/Feature/FeatureModel.h
lib/Feature/FeatureModel.cpp