vara-feature: vara::feature::ConstraintVisitor Class Reference
vara::feature::ConstraintVisitor Class Reference
#include "vara/Feature/Constraint.h"
Public Member Functions
virtual ~ConstraintVisitor ()=default
virtual bool visit (BinaryConstraint *C)
virtual bool visit (UnaryConstraint *C)
virtual bool visit (PrimaryIntegerConstraint *C)
virtual bool visit (PrimaryFeatureConstraint *C)
Detailed Description
Definition at line 632 of file Constraint.h.
Constructor & Destructor Documentation
~ConstraintVisitor()
virtual vara::feature::ConstraintVisitor::~ConstraintVisitor () virtual default
Member Function Documentation
visit() [1/4]
virtual bool vara::feature::ConstraintVisitor::visit (BinaryConstraint * C) inline virtual
Reimplemented in vara::solver::Z3SolverConstraintVisitor.
Definition at line 636 of file Constraint.h.
References vara::feature::Constraint::accept(), vara::feature::BinaryConstraint::getLeftOperand(), and vara::feature::BinaryConstraint::getRightOperand().
Referenced by vara::feature::BinaryConstraint::accept(), vara::feature::UnaryConstraint::accept(), vara::feature::PrimaryIntegerConstraint::accept(), and vara::feature::PrimaryFeatureConstraint::accept().
visit() [2/4]
virtual bool vara::feature::ConstraintVisitor::visit (PrimaryFeatureConstraint * C) inline virtual
Reimplemented in vara::solver::Z3SolverConstraintVisitor.
Definition at line 648 of file Constraint.h.
visit() [3/4]
virtual bool vara::feature::ConstraintVisitor::visit (PrimaryIntegerConstraint * C) inline virtual
Reimplemented in vara::solver::Z3SolverConstraintVisitor.
Definition at line 646 of file Constraint.h.
visit() [4/4]
virtual bool vara::feature::ConstraintVisitor::visit (UnaryConstraint * C) inline virtual
Reimplemented in vara::solver::Z3SolverConstraintVisitor.
Definition at line 642 of file Constraint.h.
References vara::feature::Constraint::accept(), and vara::feature::UnaryConstraint::getOperand().
The documentation for this class was generated from the following file:
include/vara/Feature/Constraint.h