vara-feature: vara::feature::BinaryConstraint Class Reference
vara::feature::BinaryConstraint Class Reference
#include "vara/Feature/Constraint.h"
Public Member Functions
BinaryConstraint (ConstraintKind Kind, std::unique_ptr< Constraint > LeftOperand, std::unique_ptr< Constraint > RightOperand)
Constraint * getLeftOperand () const
Constraint * getRightOperand () const
void accept (ConstraintVisitor &V) override
Public Member Functions inherited from vara::feature::Constraint
Constraint (ConstraintKind Kind)
Constraint (const Constraint &)=delete
Constraint & operator= (Constraint &)=delete
Constraint (Constraint &&)=delete
Constraint & operator= (Constraint &&)=delete
virtual ~Constraint ()=default
ConstraintKind getKind () const
void setParent (Constraint *P)
Constraint * getParent ()
Constraint * getRoot ()
virtual std::unique_ptr< Constraint > clone ()=0
Recursively clones constraint tree.
virtual std::string toString () const =0
virtual std::string toHTML () const
Protected Attributes
std::unique_ptr< Constraint > LeftOperand
std::unique_ptr< Constraint > RightOperand
Additional Inherited Members
Public Types inherited from vara::feature::Constraint
enum ConstraintKind {
ConstraintKind::CK_ADDITION, ConstraintKind::CK_AND, ConstraintKind::CK_BINARY, ConstraintKind::CK_DIVISION,
ConstraintKind::CK_EQUAL, ConstraintKind::CK_EQUIVALENCE, ConstraintKind::CK_EXCLUDES, ConstraintKind::CK_FEATURE,
ConstraintKind::CK_GREATER, ConstraintKind::CK_GREATER_EQUAL, ConstraintKind::CK_IMPLIES, ConstraintKind::CK_INTEGER,
ConstraintKind::CK_LESS, ConstraintKind::CK_LESS_EQUAL, ConstraintKind::CK_MULTIPLICATION, ConstraintKind::CK_NEG,
ConstraintKind::CK_NOT, ConstraintKind::CK_NOT_EQUAL, ConstraintKind::CK_OR, ConstraintKind::CK_PRIMARY,
ConstraintKind::CK_SUBTRACTION, ConstraintKind::CK_UNARY, ConstraintKind::CK_XOR
}
Detailed Description
Definition at line 94 of file Constraint.h.
Constructor & Destructor Documentation
BinaryConstraint()
vara::feature::BinaryConstraint::BinaryConstraint (ConstraintKind Kind, std::unique_ptr< Constraint > LeftOperand, std::unique_ptr< Constraint > RightOperand) inline
Definition at line 96 of file Constraint.h.
Member Function Documentation
accept()
void vara::feature::BinaryConstraint::accept (ConstraintVisitor & V) override virtual
Implements vara::feature::Constraint.
Definition at line 5 of file Constraint.cpp.
References vara::feature::ConstraintVisitor::visit().
getLeftOperand()
Constraint* vara::feature::BinaryConstraint::getLeftOperand () const inline
Definition at line 104 of file Constraint.h.
References LeftOperand.
Referenced by vara::feature::OrConstraint::clone(), vara::feature::XorConstraint::clone(), vara::feature::AndConstraint::clone(), vara::feature::EqualConstraint::clone(), vara::feature::NotEqualConstraint::clone(), vara::feature::ImpliesConstraint::clone(), vara::feature::ExcludesConstraint::clone(), vara::feature::EquivalenceConstraint::clone(), vara::feature::AdditionConstraint::clone(), vara::feature::SubtractionConstraint::clone(), vara::feature::MultiplicationConstraint::clone(), vara::feature::DivisionConstraint::clone(), vara::feature::LessConstraint::clone(), vara::feature::GreaterConstraint::clone(), vara::feature::LessEqualConstraint::clone(), vara::feature::GreaterEqualConstraint::clone(), and vara::feature::ConstraintVisitor::visit().
getRightOperand()
Constraint* vara::feature::BinaryConstraint::getRightOperand () const inline
Definition at line 106 of file Constraint.h.
References RightOperand.
Referenced by vara::feature::OrConstraint::clone(), vara::feature::XorConstraint::clone(), vara::feature::AndConstraint::clone(), vara::feature::EqualConstraint::clone(), vara::feature::NotEqualConstraint::clone(), vara::feature::ImpliesConstraint::clone(), vara::feature::ExcludesConstraint::clone(), vara::feature::EquivalenceConstraint::clone(), vara::feature::AdditionConstraint::clone(), vara::feature::SubtractionConstraint::clone(), vara::feature::MultiplicationConstraint::clone(), vara::feature::DivisionConstraint::clone(), vara::feature::LessConstraint::clone(), vara::feature::GreaterConstraint::clone(), vara::feature::LessEqualConstraint::clone(), vara::feature::GreaterEqualConstraint::clone(), and vara::feature::ConstraintVisitor::visit().
Member Data Documentation
LeftOperand
std::unique_ptr<Constraint> vara::feature::BinaryConstraint::LeftOperand protected
Definition at line 113 of file Constraint.h.
Referenced by getLeftOperand(), vara::feature::AndConstraint::toHTML(), vara::feature::ImpliesConstraint::toHTML(), vara::feature::ExcludesConstraint::toHTML(), vara::feature::EquivalenceConstraint::toHTML(), vara::feature::LessConstraint::toHTML(), vara::feature::GreaterConstraint::toHTML(), vara::feature::LessEqualConstraint::toHTML(), vara::feature::GreaterEqualConstraint::toHTML(), vara::feature::OrConstraint::toString(), vara::feature::XorConstraint::toString(), vara::feature::AndConstraint::toString(), vara::feature::EqualConstraint::toString(), vara::feature::NotEqualConstraint::toString(), vara::feature::ImpliesConstraint::toString(), vara::feature::ExcludesConstraint::toString(), vara::feature::EquivalenceConstraint::toString(), vara::feature::AdditionConstraint::toString(), vara::feature::SubtractionConstraint::toString(), vara::feature::MultiplicationConstraint::toString(), vara::feature::DivisionConstraint::toString(), vara::feature::LessConstraint::toString(), vara::feature::GreaterConstraint::toString(), vara::feature::LessEqualConstraint::toString(), and vara::feature::GreaterEqualConstraint::toString().
RightOperand
std::unique_ptr<Constraint> vara::feature::BinaryConstraint::RightOperand protected
Definition at line 114 of file Constraint.h.
Referenced by getRightOperand(), vara::feature::AndConstraint::toHTML(), vara::feature::ImpliesConstraint::toHTML(), vara::feature::ExcludesConstraint::toHTML(), vara::feature::EquivalenceConstraint::toHTML(), vara::feature::LessConstraint::toHTML(), vara::feature::GreaterConstraint::toHTML(), vara::feature::LessEqualConstraint::toHTML(), vara::feature::GreaterEqualConstraint::toHTML(), vara::feature::OrConstraint::toString(), vara::feature::XorConstraint::toString(), vara::feature::AndConstraint::toString(), vara::feature::EqualConstraint::toString(), vara::feature::NotEqualConstraint::toString(), vara::feature::ImpliesConstraint::toString(), vara::feature::ExcludesConstraint::toString(), vara::feature::EquivalenceConstraint::toString(), vara::feature::AdditionConstraint::toString(), vara::feature::SubtractionConstraint::toString(), vara::feature::MultiplicationConstraint::toString(), vara::feature::DivisionConstraint::toString(), vara::feature::LessConstraint::toString(), vara::feature::GreaterConstraint::toString(), vara::feature::LessEqualConstraint::toString(), and vara::feature::GreaterEqualConstraint::toString().
The documentation for this class was generated from the following files:
include/vara/Feature/Constraint.h
lib/Feature/Constraint.cpp