vara-feature: vara::solver::ConfigurationFactory Class Reference
vara::solver::ConfigurationFactory Class Reference
This class is used to retrieve information about the feature model (i.e., how many configurations are there? is it valid?)
#include "vara/Solver/ConfigurationFactory.h"
Static Public Member Functions
static ConfigurationIterable getConfigIterator (feature::FeatureModel &Model, const vara::solver::SolverType Type=SolverType::Z3)
This method returns an iterator.
static Result< SolverErrorCode, std::vector< std::unique_ptr< vara::feature::Configuration > > > getAllConfigs (feature::FeatureModel &Model, const vara::solver::SolverType Type=SolverType::Z3)
This method returns all configurations of the given feature model.
static Result< SolverErrorCode, std::vector< std::unique_ptr< vara::feature::Configuration > > > getNConfigs (feature::FeatureModel &Model, uint N, const vara::solver::SolverType Type=SolverType::Z3)
This method returns not all but the specified amount of configurations.
static bool isValid (feature::FeatureModel &Model, const vara::solver::SolverType Type=SolverType::Z3)
This method returns whether the given model has valid configurations or not.
Detailed Description
This class is used to retrieve information about the feature model (i.e., how many configurations are there? is it valid?)
Definition at line 65 of file ConfigurationFactory.h.
Member Function Documentation
getAllConfigs()
static Result<SolverErrorCode, std::vector<std::unique_ptr<vara::feature::Configuration> > > vara::solver::ConfigurationFactory::getAllConfigs (feature::FeatureModel & Model, const vara::solver::SolverType Type = SolverType::Z3) inline static
This method returns all configurations of the given feature model.
Note that retrieving all configurations might take some time or even be infeasible, especially for larger feature models.
Parameters
Model the given model containing the features and constraints
Type the type of solver to use
Returns
a unique pointer to the vector containing all configurations
Definition at line 91 of file ConfigurationFactory.h.
References vara::solver::SolverFactory::initializeSolver().
getConfigIterator()
static ConfigurationIterable vara::solver::ConfigurationFactory::getConfigIterator (feature::FeatureModel & Model, const vara::solver::SolverType Type = SolverType::Z3) inline static
This method returns an iterator.
This iterator can be used to lazily traverse over configurations retrieved by the solver.
Parameters
Model the given model containing the features and constraints
Type the type of solver to use
Returns
A unique pointer to the configuration iterator
Definition at line 75 of file ConfigurationFactory.h.
References vara::solver::SolverFactory::initializeSolver().
Referenced by getNConfigs().
getNConfigs()
static Result<SolverErrorCode, std::vector<std::unique_ptr<vara::feature::Configuration> > > vara::solver::ConfigurationFactory::getNConfigs (feature::FeatureModel & Model, uint N, const vara::solver::SolverType Type = SolverType::Z3) inline static
This method returns not all but the specified amount of configurations.
Note that the vector can also contain less configurations if there are not enough valid configurations.
Parameters
Model the given model containing the features and constraints
N the number of configurations to retrieve
Type the type of the solver
Returns
a unique pointer to a vector containing the specified amount of configurations.
Definition at line 109 of file ConfigurationFactory.h.
References getConfigIterator().
isValid()
static bool vara::solver::ConfigurationFactory::isValid (feature::FeatureModel & Model, const vara::solver::SolverType Type = SolverType::Z3) inline static
This method returns whether the given model has valid configurations or not.
Parameters
Model the model containing the features and constraints
Type the type of solver to use
Returns
true iff there is at least one valid configuration
Definition at line 134 of file ConfigurationFactory.h.
References vara::solver::SolverFactory::initializeSolver().
The documentation for this class was generated from the following file:
include/vara/Solver/ConfigurationFactory.h