# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michael/Documents/vara-feature

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michael/Documents/vara-feature

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Documents/vara-feature/CMakeFiles /home/michael/Documents/vara-feature//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Documents/vara-feature/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/michael/Documents/vara-feature/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tidy-vara-feature

# Build rule for target.
tidy-vara-feature: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tidy-vara-feature
.PHONY : tidy-vara-feature

# fast build rule for target.
tidy-vara-feature/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tidy-vara-feature.dir/build.make CMakeFiles/tidy-vara-feature.dir/build
.PHONY : tidy-vara-feature/fast

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISCVTargetParserTableGen.dir/build.make CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named csv

# Build rule for target.
csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csv
.PHONY : csv

# fast build rule for target.
csv/fast:
	$(MAKE) $(MAKESILENT) -f external/csv-parser/include/internal/CMakeFiles/csv.dir/build.make external/csv-parser/include/internal/CMakeFiles/csv.dir/build
.PHONY : csv/fast

#=============================================================================
# Target rules for targets named csv_info

# Build rule for target.
csv_info: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csv_info
.PHONY : csv_info

# fast build rule for target.
csv_info/fast:
	$(MAKE) $(MAKESILENT) -f external/csv-parser/programs/CMakeFiles/csv_info.dir/build.make external/csv-parser/programs/CMakeFiles/csv_info.dir/build
.PHONY : csv_info/fast

#=============================================================================
# Target rules for targets named csv_stats

# Build rule for target.
csv_stats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csv_stats
.PHONY : csv_stats

# fast build rule for target.
csv_stats/fast:
	$(MAKE) $(MAKESILENT) -f external/csv-parser/programs/CMakeFiles/csv_stats.dir/build.make external/csv-parser/programs/CMakeFiles/csv_stats.dir/build
.PHONY : csv_stats/fast

#=============================================================================
# Target rules for targets named VaRAConfiguration

# Build rule for target.
VaRAConfiguration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRAConfiguration
.PHONY : VaRAConfiguration

# fast build rule for target.
VaRAConfiguration/fast:
	$(MAKE) $(MAKESILENT) -f lib/Configuration/CMakeFiles/VaRAConfiguration.dir/build.make lib/Configuration/CMakeFiles/VaRAConfiguration.dir/build
.PHONY : VaRAConfiguration/fast

#=============================================================================
# Target rules for targets named VaRAFeature

# Build rule for target.
VaRAFeature: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRAFeature
.PHONY : VaRAFeature

# fast build rule for target.
VaRAFeature/fast:
	$(MAKE) $(MAKESILENT) -f lib/Feature/CMakeFiles/VaRAFeature.dir/build.make lib/Feature/CMakeFiles/VaRAFeature.dir/build
.PHONY : VaRAFeature/fast

#=============================================================================
# Target rules for targets named VaRASampling

# Build rule for target.
VaRASampling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRASampling
.PHONY : VaRASampling

# fast build rule for target.
VaRASampling/fast:
	$(MAKE) $(MAKESILENT) -f lib/Sampling/CMakeFiles/VaRASampling.dir/build.make lib/Sampling/CMakeFiles/VaRASampling.dir/build
.PHONY : VaRASampling/fast

#=============================================================================
# Target rules for targets named VaRASolver

# Build rule for target.
VaRASolver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRASolver
.PHONY : VaRASolver

# fast build rule for target.
VaRASolver/fast:
	$(MAKE) $(MAKESILENT) -f lib/Solver/CMakeFiles/VaRASolver.dir/build.make lib/Solver/CMakeFiles/VaRASolver.dir/build
.PHONY : VaRASolver/fast

#=============================================================================
# Target rules for targets named fm-viewer

# Build rule for target.
fm-viewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fm-viewer
.PHONY : fm-viewer

# fast build rule for target.
fm-viewer/fast:
	$(MAKE) $(MAKESILENT) -f tools/fm-viewer/CMakeFiles/fm-viewer.dir/build.make tools/fm-viewer/CMakeFiles/fm-viewer.dir/build
.PHONY : fm-viewer/fast

#=============================================================================
# Target rules for targets named check-vara-fm-viewer

# Build rule for target.
check-vara-fm-viewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-vara-fm-viewer
.PHONY : check-vara-fm-viewer

# fast build rule for target.
check-vara-fm-viewer/fast:
	$(MAKE) $(MAKESILENT) -f tools/fm-viewer/CMakeFiles/check-vara-fm-viewer.dir/build.make tools/fm-viewer/CMakeFiles/check-vara-fm-viewer.dir/build
.PHONY : check-vara-fm-viewer/fast

#=============================================================================
# Target rules for targets named vara_feature

# Build rule for target.
vara_feature: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vara_feature
.PHONY : vara_feature

# fast build rule for target.
vara_feature/fast:
	$(MAKE) $(MAKESILENT) -f bindings/python/vara-feature/CMakeFiles/vara_feature.dir/build.make bindings/python/vara-feature/CMakeFiles/vara_feature.dir/build
.PHONY : vara_feature/fast

#=============================================================================
# Target rules for targets named check-vara-feature-python

# Build rule for target.
check-vara-feature-python: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-vara-feature-python
.PHONY : check-vara-feature-python

# fast build rule for target.
check-vara-feature-python/fast:
	$(MAKE) $(MAKESILENT) -f bindings/python/tests/CMakeFiles/check-vara-feature-python.dir/build.make bindings/python/tests/CMakeFiles/check-vara-feature-python.dir/build
.PHONY : check-vara-feature-python/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f external/googletest/googlemock/CMakeFiles/gmock.dir/build.make external/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f external/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make external/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f external/googletest/googletest/CMakeFiles/gtest.dir/build.make external/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f external/googletest/googletest/CMakeFiles/gtest_main.dir/build.make external/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named VaRAFeatureUnitTests

# Build rule for target.
VaRAFeatureUnitTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRAFeatureUnitTests
.PHONY : VaRAFeatureUnitTests

# fast build rule for target.
VaRAFeatureUnitTests/fast:
	$(MAKE) $(MAKESILENT) -f unittests/CMakeFiles/VaRAFeatureUnitTests.dir/build.make unittests/CMakeFiles/VaRAFeatureUnitTests.dir/build
.PHONY : VaRAFeatureUnitTests/fast

#=============================================================================
# Target rules for targets named VaRAConfigurationUnitTests

# Build rule for target.
VaRAConfigurationUnitTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRAConfigurationUnitTests
.PHONY : VaRAConfigurationUnitTests

# fast build rule for target.
VaRAConfigurationUnitTests/fast:
	$(MAKE) $(MAKESILENT) -f unittests/CMakeFiles/VaRAConfigurationUnitTests.dir/build.make unittests/CMakeFiles/VaRAConfigurationUnitTests.dir/build
.PHONY : VaRAConfigurationUnitTests/fast

#=============================================================================
# Target rules for targets named VaRASamplingUnitTests

# Build rule for target.
VaRASamplingUnitTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRASamplingUnitTests
.PHONY : VaRASamplingUnitTests

# fast build rule for target.
VaRASamplingUnitTests/fast:
	$(MAKE) $(MAKESILENT) -f unittests/CMakeFiles/VaRASamplingUnitTests.dir/build.make unittests/CMakeFiles/VaRASamplingUnitTests.dir/build
.PHONY : VaRASamplingUnitTests/fast

#=============================================================================
# Target rules for targets named VaRASolverUnitTests

# Build rule for target.
VaRASolverUnitTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRASolverUnitTests
.PHONY : VaRASolverUnitTests

# fast build rule for target.
VaRASolverUnitTests/fast:
	$(MAKE) $(MAKESILENT) -f unittests/CMakeFiles/VaRASolverUnitTests.dir/build.make unittests/CMakeFiles/VaRASolverUnitTests.dir/build
.PHONY : VaRASolverUnitTests/fast

#=============================================================================
# Target rules for targets named check-vara-feature-unittests

# Build rule for target.
check-vara-feature-unittests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-vara-feature-unittests
.PHONY : check-vara-feature-unittests

# fast build rule for target.
check-vara-feature-unittests/fast:
	$(MAKE) $(MAKESILENT) -f unittests/CMakeFiles/check-vara-feature-unittests.dir/build.make unittests/CMakeFiles/check-vara-feature-unittests.dir/build
.PHONY : check-vara-feature-unittests/fast

#=============================================================================
# Target rules for targets named VaRAConfigurationTests

# Build rule for target.
VaRAConfigurationTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRAConfigurationTests
.PHONY : VaRAConfigurationTests

# fast build rule for target.
VaRAConfigurationTests/fast:
	$(MAKE) $(MAKESILENT) -f unittests/Configuration/CMakeFiles/VaRAConfigurationTests.dir/build.make unittests/Configuration/CMakeFiles/VaRAConfigurationTests.dir/build
.PHONY : VaRAConfigurationTests/fast

#=============================================================================
# Target rules for targets named VaRAFeatureTests

# Build rule for target.
VaRAFeatureTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRAFeatureTests
.PHONY : VaRAFeatureTests

# fast build rule for target.
VaRAFeatureTests/fast:
	$(MAKE) $(MAKESILENT) -f unittests/Feature/CMakeFiles/VaRAFeatureTests.dir/build.make unittests/Feature/CMakeFiles/VaRAFeatureTests.dir/build
.PHONY : VaRAFeatureTests/fast

#=============================================================================
# Target rules for targets named VaRASamplingTests

# Build rule for target.
VaRASamplingTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRASamplingTests
.PHONY : VaRASamplingTests

# fast build rule for target.
VaRASamplingTests/fast:
	$(MAKE) $(MAKESILENT) -f unittests/Sampling/CMakeFiles/VaRASamplingTests.dir/build.make unittests/Sampling/CMakeFiles/VaRASamplingTests.dir/build
.PHONY : VaRASamplingTests/fast

#=============================================================================
# Target rules for targets named VaRAVariantUtilsTests

# Build rule for target.
VaRAVariantUtilsTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaRAVariantUtilsTests
.PHONY : VaRAVariantUtilsTests

# fast build rule for target.
VaRAVariantUtilsTests/fast:
	$(MAKE) $(MAKESILENT) -f unittests/Utils/CMakeFiles/VaRAVariantUtilsTests.dir/build.make unittests/Utils/CMakeFiles/VaRAVariantUtilsTests.dir/build
.PHONY : VaRAVariantUtilsTests/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/Experimental.dir/build.make external/oxidd/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/Nightly.dir/build.make external/oxidd/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/Continuous.dir/build.make external/oxidd/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/NightlyMemoryCheck.dir/build.make external/oxidd/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/NightlyStart.dir/build.make external/oxidd/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/NightlyUpdate.dir/build.make external/oxidd/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/NightlyConfigure.dir/build.make external/oxidd/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/NightlyBuild.dir/build.make external/oxidd/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/NightlyTest.dir/build.make external/oxidd/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/NightlyCoverage.dir/build.make external/oxidd/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/NightlyMemCheck.dir/build.make external/oxidd/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/NightlySubmit.dir/build.make external/oxidd/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ExperimentalStart.dir/build.make external/oxidd/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ExperimentalUpdate.dir/build.make external/oxidd/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ExperimentalConfigure.dir/build.make external/oxidd/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ExperimentalBuild.dir/build.make external/oxidd/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ExperimentalTest.dir/build.make external/oxidd/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ExperimentalCoverage.dir/build.make external/oxidd/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ExperimentalMemCheck.dir/build.make external/oxidd/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ExperimentalSubmit.dir/build.make external/oxidd/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ContinuousStart.dir/build.make external/oxidd/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ContinuousUpdate.dir/build.make external/oxidd/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ContinuousConfigure.dir/build.make external/oxidd/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ContinuousBuild.dir/build.make external/oxidd/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ContinuousTest.dir/build.make external/oxidd/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ContinuousCoverage.dir/build.make external/oxidd/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ContinuousMemCheck.dir/build.make external/oxidd/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/ContinuousSubmit.dir/build.make external/oxidd/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named oxidd-capi-header

# Build rule for target.
oxidd-capi-header: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 oxidd-capi-header
.PHONY : oxidd-capi-header

# fast build rule for target.
oxidd-capi-header/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/oxidd-capi-header.dir/build.make external/oxidd/CMakeFiles/oxidd-capi-header.dir/build
.PHONY : oxidd-capi-header/fast

#=============================================================================
# Target rules for targets named _cargo-build_oxidd_ffi_c

# Build rule for target.
_cargo-build_oxidd_ffi_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _cargo-build_oxidd_ffi_c
.PHONY : _cargo-build_oxidd_ffi_c

# fast build rule for target.
_cargo-build_oxidd_ffi_c/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/_cargo-build_oxidd_ffi_c.dir/build.make external/oxidd/CMakeFiles/_cargo-build_oxidd_ffi_c.dir/build
.PHONY : _cargo-build_oxidd_ffi_c/fast

#=============================================================================
# Target rules for targets named cargo-build_oxidd_ffi_c

# Build rule for target.
cargo-build_oxidd_ffi_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cargo-build_oxidd_ffi_c
.PHONY : cargo-build_oxidd_ffi_c

# fast build rule for target.
cargo-build_oxidd_ffi_c/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/cargo-build_oxidd_ffi_c.dir/build.make external/oxidd/CMakeFiles/cargo-build_oxidd_ffi_c.dir/build
.PHONY : cargo-build_oxidd_ffi_c/fast

#=============================================================================
# Target rules for targets named cargo-prebuild_oxidd_ffi_c

# Build rule for target.
cargo-prebuild_oxidd_ffi_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cargo-prebuild_oxidd_ffi_c
.PHONY : cargo-prebuild_oxidd_ffi_c

# fast build rule for target.
cargo-prebuild_oxidd_ffi_c/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/cargo-prebuild_oxidd_ffi_c.dir/build.make external/oxidd/CMakeFiles/cargo-prebuild_oxidd_ffi_c.dir/build
.PHONY : cargo-prebuild_oxidd_ffi_c/fast

#=============================================================================
# Target rules for targets named cargo-prebuild

# Build rule for target.
cargo-prebuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cargo-prebuild
.PHONY : cargo-prebuild

# fast build rule for target.
cargo-prebuild/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/cargo-prebuild.dir/build.make external/oxidd/CMakeFiles/cargo-prebuild.dir/build
.PHONY : cargo-prebuild/fast

#=============================================================================
# Target rules for targets named cargo-clean_oxidd_ffi_c

# Build rule for target.
cargo-clean_oxidd_ffi_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cargo-clean_oxidd_ffi_c
.PHONY : cargo-clean_oxidd_ffi_c

# fast build rule for target.
cargo-clean_oxidd_ffi_c/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/cargo-clean_oxidd_ffi_c.dir/build.make external/oxidd/CMakeFiles/cargo-clean_oxidd_ffi_c.dir/build
.PHONY : cargo-clean_oxidd_ffi_c/fast

#=============================================================================
# Target rules for targets named cargo-clean

# Build rule for target.
cargo-clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cargo-clean
.PHONY : cargo-clean

# fast build rule for target.
cargo-clean/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/CMakeFiles/cargo-clean.dir/build.make external/oxidd/CMakeFiles/cargo-clean.dir/build
.PHONY : cargo-clean/fast

#=============================================================================
# Target rules for targets named boolean-function

# Build rule for target.
boolean-function: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boolean-function
.PHONY : boolean-function

# fast build rule for target.
boolean-function/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/bindings/cpp/tests/CMakeFiles/boolean-function.dir/build.make external/oxidd/bindings/cpp/tests/CMakeFiles/boolean-function.dir/build
.PHONY : boolean-function/fast

#=============================================================================
# Target rules for targets named dump-dot

# Build rule for target.
dump-dot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dump-dot
.PHONY : dump-dot

# fast build rule for target.
dump-dot/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/bindings/cpp/examples/CMakeFiles/dump-dot.dir/build.make external/oxidd/bindings/cpp/examples/CMakeFiles/dump-dot.dir/build
.PHONY : dump-dot/fast

#=============================================================================
# Target rules for targets named import

# Build rule for target.
import: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 import
.PHONY : import

# fast build rule for target.
import/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/bindings/cpp/examples/CMakeFiles/import.dir/build.make external/oxidd/bindings/cpp/examples/CMakeFiles/import.dir/build
.PHONY : import/fast

#=============================================================================
# Target rules for targets named export

# Build rule for target.
export: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 export
.PHONY : export

# fast build rule for target.
export/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/bindings/cpp/examples/CMakeFiles/export.dir/build.make external/oxidd/bindings/cpp/examples/CMakeFiles/export.dir/build
.PHONY : export/fast

#=============================================================================
# Target rules for targets named visualize

# Build rule for target.
visualize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 visualize
.PHONY : visualize

# fast build rule for target.
visualize/fast:
	$(MAKE) $(MAKESILENT) -f external/oxidd/bindings/cpp/examples/CMakeFiles/visualize.dir/build.make external/oxidd/bindings/cpp/examples/CMakeFiles/visualize.dir/build
.PHONY : visualize/fast

#=============================================================================
# Target rules for targets named coverage_lib

# Build rule for target.
coverage_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coverage_lib
.PHONY : coverage_lib

# fast build rule for target.
coverage_lib/fast:
	$(MAKE) $(MAKESILENT) -f Random_Sampler/CMakeFiles/coverage_lib.dir/build.make Random_Sampler/CMakeFiles/coverage_lib.dir/build
.PHONY : coverage_lib/fast

#=============================================================================
# Target rules for targets named random_sampler

# Build rule for target.
random_sampler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 random_sampler
.PHONY : random_sampler

# fast build rule for target.
random_sampler/fast:
	$(MAKE) $(MAKESILENT) -f Random_Sampler/CMakeFiles/random_sampler.dir/build.make Random_Sampler/CMakeFiles/random_sampler.dir/build
.PHONY : random_sampler/fast

#=============================================================================
# Target rules for targets named bdd

# Build rule for target.
bdd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bdd
.PHONY : bdd

# fast build rule for target.
bdd/fast:
	$(MAKE) $(MAKESILENT) -f BDD/CMakeFiles/bdd.dir/build.make BDD/CMakeFiles/bdd.dir/build
.PHONY : bdd/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... RISCVTargetParserTableGen"
	@echo "... VaRAConfigurationUnitTests"
	@echo "... VaRAFeatureUnitTests"
	@echo "... VaRASamplingUnitTests"
	@echo "... VaRASolverUnitTests"
	@echo "... _cargo-build_oxidd_ffi_c"
	@echo "... acc_gen"
	@echo "... cargo-build_oxidd_ffi_c"
	@echo "... cargo-clean"
	@echo "... cargo-clean_oxidd_ffi_c"
	@echo "... cargo-prebuild"
	@echo "... cargo-prebuild_oxidd_ffi_c"
	@echo "... check-vara-feature-python"
	@echo "... check-vara-feature-unittests"
	@echo "... check-vara-fm-viewer"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... oxidd-capi-header"
	@echo "... tidy-vara-feature"
	@echo "... VaRAConfiguration"
	@echo "... VaRAConfigurationTests"
	@echo "... VaRAFeature"
	@echo "... VaRAFeatureTests"
	@echo "... VaRASampling"
	@echo "... VaRASamplingTests"
	@echo "... VaRASolver"
	@echo "... VaRAVariantUtilsTests"
	@echo "... bdd"
	@echo "... boolean-function"
	@echo "... coverage_lib"
	@echo "... csv"
	@echo "... csv_info"
	@echo "... csv_stats"
	@echo "... dump-dot"
	@echo "... export"
	@echo "... fm-viewer"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... import"
	@echo "... random_sampler"
	@echo "... vara_feature"
	@echo "... visualize"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/michael/Documents/vara-feature/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

