vara-feature: vara::feature Namespace Reference
vara::feature Namespace Reference
Namespaces
deprecated
detail
Classes
class AdditionConstraint
class AndConstraint
class BinaryConstraint
class BinaryFeature
Options without arguments.
class BooleanConstraint
struct CheckFeatureParentChildRelationShip
class Configuration
This class represents a configuration.
class ConfigurationOption
This class represents a simple configuration option.
class Constraint
Tree like representation of constraints between features.
class ConstraintLexer
class ConstraintParser
class ConstraintToken
class ConstraintVisitor
class DivisionConstraint
class EqualConstraint
class EquivalenceConstraint
struct EveryFeatureRequiresParent
struct ExactlyOneRootNode
class ExcludesConstraint
class Feature
Base class for components of FeatureModel.
class FeatureModel
Tree like representation of features and dependencies.
class FeatureModelBuilder
Builder for FeatureModel which can be used while parsing.
class FeatureModelConsistencyChecker
class FeatureModelParser
Base class for parsers with different input formats.
class FeatureModelSxfmParser
Parsers for feature models in SXFM.
class FeatureModelTransaction
class FeatureModelWriter
Base class for parsers with different input formats.
class FeatureModelXmlParser
Parsers for feature models in XML.
class FeatureModelXmlWriter
Parsers for feature models in XML.
class FeatureSourceRange
class FeatureTreeNode
class GreaterConstraint
class GreaterEqualConstraint
class ImpliesConstraint
class LessConstraint
class LessEqualConstraint
class MultiplicationConstraint
class NegConstraint
class NotConstraint
class NotEqualConstraint
class NumericConstraint
class NumericFeature
Options with numeric values.
class OrConstraint
class PrimaryConstraint
class PrimaryFeatureConstraint
class PrimaryIntegerConstraint
class Relationship
class RootFeature
class StepFunction
class StepFunctionLexer
class StepFunctionParser
class StepFunctionToken
class SubtractionConstraint
class SxfmConstants
class UnaryConstraint
class XmlConstants
class XorConstraint
Typedefs
using FeatureModelCopyTransaction = FeatureModelTransaction< detail::CopyTransactionMode >
using FeatureModelModifyTransaction = FeatureModelTransaction< detail::ModifyTransactionMode >
Enumerations
enum FTErrorCode {
ABORTED, ALREADY_PRESENT, ERROR, INCONSISTENT,
MISSING_FEATURE, MISSING_MODEL, MISSING_PARENT, MISSING_CHILD,
NON_LEAF_NODE, RECURSIVE_EDGE
}
Functions
static int64_t parseInteger (llvm::StringRef Str, std::optional< unsigned int > Line=std::nullopt)
Parse 64-bit integer in decimal or scientific notation.
std::unique_ptr< FeatureModel > loadFeatureModel (llvm::StringRef Path)
bool verifyFeatureModel (llvm::StringRef Path)
void addFeature (FeatureModel &FM, std::unique_ptr< Feature > NewFeature, Feature *Parent=nullptr)
Adds a Feature to the FeatureModel.
void addFeatures (FeatureModel &FM, std::vector< std::pair< std::unique_ptr< Feature >, Feature * >> NewFeatures)
Adds multiple Features to the FeatureModel.
void removeFeature (FeatureModel &FM, detail::FeatureVariantTy FeatureToBeDeleted, bool Recursive=false)
Removes a Feature from the FeatureModel.
std::vector< detail::FeatureVariantTy > removeFeatures (FeatureModel &FM, std::vector< detail::FeatureVariantTy >::iterator Begin, std::vector< detail::FeatureVariantTy >::iterator End, bool Recursive=false)
Removes multiple Features from the FeatureModel.
std::vector< detail::FeatureVariantTy > removeFeatures (FeatureModel &FM, std::vector< detail::FeatureVariantTy > FeaturesToBeDeleted, bool Recursive=false)
Removes multiple Features from the FeatureModel.
void addRelationship (FeatureModel &FM, const detail::FeatureVariantTy &GroupRoot, Relationship::RelationshipKind Kind)
Adds a Relationship to a Feature.
void removeRelationship (FeatureModel &FM, const detail::FeatureVariantTy &GroupRoot)
Removes the Relationship from Group.
void setCommit (FeatureModel &FM, std::string NewCommit)
Set commit of a FeatureModel.
std::unique_ptr< FeatureModel > mergeFeatureModels (FeatureModel &FM1, FeatureModel &FM2, bool Strict=true)
Merges a FeatureModel into another.
std::unique_ptr< FeatureModel > loadXMLFeatureModelFromBuffer (std::string FileContent)
std::unique_ptr< FeatureModel > loadFeatureModelFromBuffer (std::string FileContent)
bool verifyXMLFeatureModelFromBuffer (std::string FileContent)
bool verifyFeatureModelFromBuffer (std::string FileContent)
std::string trim (llvm::StringRef S)
template<>
Result< FTErrorCode > FeatureModelXmlParser::parseConstraints< FeatureModel::MixedConstraint > (xmlNode *Node)
bool detectExclude (const Feature *A, const Feature *B)
Decide whether feature A excludes B.
bool mergeSubtree (FeatureModelCopyTransaction &Trans, FeatureModel const &FM, Feature &F, bool Strict)
std::unique_ptr< Feature > featureCopy (Feature &F)
bool compareProperties (const Feature &F1, const Feature &F2, bool Strict)
Feature * getActualFeature (FeatureModel &FM, detail::FeatureVariantTy &FV)
std::optional< bool > fvIsLeaf (FeatureModel &FM, detail::FeatureVariantTy &FV)
std::optional< bool > canBeDeletedRecursively (FeatureModel &FM, detail::FeatureVariantTy &FV, const std::set< FeatureTreeNode * > &OtherFeatures)
Checks if in recursive mode the provided Feature can be deleted or not.
const unsigned char * charToUChar (const char *CP)
Variables
static constexpr xmlChar INDENTATIONSTRING [] = " "
static constexpr char ENCODING [] = "UTF-8"
Typedef Documentation
FeatureModelCopyTransaction
using vara::feature::FeatureModelCopyTransaction = typedef FeatureModelTransaction<detail::CopyTransactionMode>
Definition at line 172 of file FeatureModelTransaction.h.
FeatureModelModifyTransaction
using vara::feature::FeatureModelModifyTransaction = typedef FeatureModelTransaction<detail::ModifyTransactionMode>
Definition at line 174 of file FeatureModelTransaction.h.
Enumeration Type Documentation
FTErrorCode
enum vara::feature::FTErrorCode
Enumerator
ABORTED
ALREADY_PRESENT
ERROR
INCONSISTENT
MISSING_FEATURE
MISSING_MODEL
MISSING_PARENT
MISSING_CHILD
NON_LEAF_NODE
RECURSIVE_EDGE
Definition at line 17 of file Error.h.
Function Documentation
addFeature()
void vara::feature::addFeature (FeatureModel & FM, std::unique_ptr< Feature > NewFeature, Feature * Parent = nullptr)
Adds a Feature to the FeatureModel.
If a Parent is passed it needs to be already in the FeatureModel, otherwise, root is assumed as the parent Feature.
Parameters
FM
NewFeature
Parent of the new feature
Definition at line 17 of file FeatureModelTransaction.cpp.
References vara::feature::FeatureModelTransaction< CopyMode >::openTransaction().
Referenced by vara::feature::FeatureModel::FeatureModel().
addFeatures()
void vara::feature::addFeatures (FeatureModel & FM, std::vector< std::pair< std::unique_ptr< Feature >, Feature * >> NewFeatures)
Adds multiple Features to the FeatureModel.
The vector of Features contains tuples of a new Feature and a parent. If a Parent is passed it needs to be already in the FeatureModel, otherwise, root is assumed as the parent Feature.
Parameters
FM
NewFeatures
Definition at line 24 of file FeatureModelTransaction.cpp.
References vara::feature::FeatureModelTransaction< CopyMode >::openTransaction().
addRelationship()
void vara::feature::addRelationship (FeatureModel & FM, const detail::FeatureVariantTy & GroupRoot, Relationship::RelationshipKind Kind)
Adds a Relationship to a Feature.
Parameters
FM
GroupRoot of relationship group
Kind of relationship
Definition at line 141 of file FeatureModelTransaction.cpp.
References vara::feature::FeatureModelTransaction< CopyMode >::openTransaction().
canBeDeletedRecursively()
std::optional<bool> vara::feature::canBeDeletedRecursively (FeatureModel & FM, detail::FeatureVariantTy & FV, const std::set< FeatureTreeNode * > & OtherFeatures)
Checks if in recursive mode the provided Feature can be deleted or not.
Parameters
FM
FV
OtherFeatures
Returns
optional of true, if all transitive children of FV are not part of OtherFeatures; optional of false, if at least one transitive child of FV is part of OtherFeatures; nullopt, if FV is not part of FM
Definition at line 70 of file FeatureModelTransaction.cpp.
References getActualFeature(), and vara::feature::FeatureTreeNode::getChildren().
Referenced by removeFeatures().
charToUChar()
const unsigned char* vara::feature::charToUChar (const char * CP)
Definition at line 18 of file FeatureModelWriter.cpp.
compareProperties()
bool vara::feature::compareProperties (const Feature & F1, const Feature & F2, bool Strict)
Definition at line 228 of file FeatureModelTransaction.cpp.
References vara::feature::Feature::FK_BINARY, vara::feature::Feature::FK_ROOT, vara::feature::FeatureTreeNode::getKind(), vara::feature::Feature::getKind(), vara::feature::Feature::getName(), vara::feature::FeatureTreeNode::getParent(), vara::feature::Feature::getParentFeature(), and vara::feature::Feature::isOptional().
Referenced by mergeSubtree().
detectExclude()
bool vara::feature::detectExclude (const Feature * A, const Feature * B)
Decide whether feature A excludes B.
Beware that this method only detects very simple trees with binary excludes.
Definition at line 358 of file FeatureModelParser.cpp.
References vara::feature::Feature::excludes().
featureCopy()
std::unique_ptr< Feature > vara::feature::featureCopy (Feature & F)
Definition at line 205 of file FeatureModelTransaction.cpp.
References vara::feature::Feature::FK_BINARY, vara::feature::Feature::FK_NUMERIC, vara::feature::Feature::FK_ROOT, vara::feature::Feature::getKind(), vara::feature::Feature::getLocationsBegin(), vara::feature::Feature::getLocationsEnd(), vara::feature::Feature::getName(), and vara::feature::Feature::isOptional().
Referenced by mergeSubtree().
FeatureModelXmlParser::parseConstraints< FeatureModel::MixedConstraint >()
template<> Result<FTErrorCode> vara::feature::FeatureModelXmlParser::parseConstraints< FeatureModel::MixedConstraint > (xmlNode * Node)
Definition at line 243 of file FeatureModelParser.cpp.
References vara::feature::FeatureModel::MixedConstraint::ALL, vara::feature::ConstraintParser::buildConstraint(), vara::feature::XmlConstants::CONSTRAINT, ERROR, vara::feature::XmlConstants::EXPRKIND, vara::feature::FeatureModel::MixedConstraint::NEG, vara::feature::FeatureModel::MixedConstraint::NONE, vara::feature::FeatureModel::MixedConstraint::POS, and vara::feature::XmlConstants::REQ.
fvIsLeaf()
std::optional<bool> vara::feature::fvIsLeaf (FeatureModel & FM, detail::FeatureVariantTy & FV)
Definition at line 52 of file FeatureModelTransaction.cpp.
References getActualFeature(), and vara::feature::FeatureTreeNode::isLeaf().
Referenced by removeFeatures().
getActualFeature()
Feature* vara::feature::getActualFeature (FeatureModel & FM, detail::FeatureVariantTy & FV)
Definition at line 42 of file FeatureModelTransaction.cpp.
References vara::feature::FeatureModel::getFeature().
Referenced by canBeDeletedRecursively(), and fvIsLeaf().
loadFeatureModel()
std::unique_ptr< FeatureModel > vara::feature::loadFeatureModel (llvm::StringRef Path)
Definition at line 130 of file FeatureModel.cpp.
References loadFeatureModelFromBuffer().
loadFeatureModelFromBuffer()
std::unique_ptr<FeatureModel> vara::feature::loadFeatureModelFromBuffer (std::string FileContent)
Definition at line 125 of file FeatureModel.cpp.
References loadXMLFeatureModelFromBuffer().
Referenced by loadFeatureModel().
loadXMLFeatureModelFromBuffer()
std::unique_ptr<FeatureModel> vara::feature::loadXMLFeatureModelFromBuffer (std::string FileContent)
Definition at line 120 of file FeatureModel.cpp.
References vara::feature::FeatureModelXmlParser::buildFeatureModel().
Referenced by loadFeatureModelFromBuffer().
mergeFeatureModels()
std::unique_ptr< FeatureModel > vara::feature::mergeFeatureModels (FeatureModel & FM1, FeatureModel & FM2, bool Strict = true)
Merges a FeatureModel into another.
Strict merging fails if both FeatureModels contain a Feature with equal name, but different properties. Non-strict merging prefers properties of Feature in FM1.
Parameters
FM1
FM2
Strict mode
Returns
New merged FeatureModel or nullptr if merging failed
Definition at line 163 of file FeatureModelTransaction.cpp.
References vara::feature::FeatureModel::getRoot(), mergeSubtree(), and vara::feature::FeatureModelTransaction< CopyMode >::openTransaction().
mergeSubtree()
bool vara::feature::mergeSubtree (FeatureModelCopyTransaction & Trans, FeatureModel const & FM, Feature & F, bool Strict)
Definition at line 172 of file FeatureModelTransaction.cpp.
References vara::feature::FeatureModelTransaction< CopyMode >::addFeature(), vara::feature::FeatureModelTransaction< CopyMode >::addLocation(), compareProperties(), featureCopy(), vara::feature::FeatureTreeNode::getChildren(), vara::feature::FeatureModel::getFeature(), vara::feature::Feature::getLocations(), vara::feature::Feature::getName(), and vara::feature::Feature::getParentFeature().
Referenced by mergeFeatureModels().
parseInteger()
static int64_t vara::feature::parseInteger (llvm::StringRef Str, std::optional< unsigned int > Line = std::nullopt) static
Parse 64-bit integer in decimal or scientific notation.
Definition at line 266 of file ConstraintParser.h.
removeFeature()
void vara::feature::removeFeature (FeatureModel & FM, detail::FeatureVariantTy FeatureToBeDeleted, bool Recursive = false)
Removes a Feature from the FeatureModel.
Parameters
FM
FeatureToBeDeleted
Definition at line 34 of file FeatureModelTransaction.cpp.
References vara::feature::FeatureModelTransaction< CopyMode >::openTransaction().
removeFeatures() [1/2]
std::vector<detail::FeatureVariantTy> vara::feature::removeFeatures (FeatureModel & FM, std::vector< detail::FeatureVariantTy > FeaturesToBeDeleted, bool Recursive = false) inline
Removes multiple Features from the FeatureModel.
Parameters
FM
FeaturesToBeDeleted
Recursive
Returns
Vector of all FeatureVariants, that cannot be deleted
Definition at line 1157 of file FeatureModelTransaction.h.
References vara::feature::FeatureModel::begin(), and removeFeatures().
removeFeatures() [2/2]
std::vector< detail::FeatureVariantTy > vara::feature::removeFeatures (FeatureModel & FM, std::vector< detail::FeatureVariantTy >::iterator Begin, std::vector< detail::FeatureVariantTy >::iterator End, bool Recursive = false)
Removes multiple Features from the FeatureModel.
Parameters
FM
Begin
End
Recursive
Returns
Vector of all FeatureVariants, that cannot be deleted
Definition at line 88 of file FeatureModelTransaction.cpp.
References canBeDeletedRecursively(), fvIsLeaf(), and vara::feature::FeatureModelTransaction< CopyMode >::openTransaction().
Referenced by removeFeatures().
removeRelationship()
void vara::feature::removeRelationship (FeatureModel & FM, const detail::FeatureVariantTy & GroupRoot)
Removes the Relationship from Group.
Parameters
FM
GroupRoot of Relationship
Definition at line 149 of file FeatureModelTransaction.cpp.
References vara::feature::FeatureModelTransaction< CopyMode >::openTransaction().
setCommit()
void vara::feature::setCommit (FeatureModel & FM, std::string NewCommit)
Set commit of a FeatureModel.
Parameters
FM
NewCommit
Definition at line 156 of file FeatureModelTransaction.cpp.
References vara::feature::FeatureModelTransaction< CopyMode >::openTransaction().
trim()
std::string vara::feature::trim (llvm::StringRef S)
Definition at line 21 of file FeatureModelParser.cpp.
verifyFeatureModel()
bool vara::feature::verifyFeatureModel (llvm::StringRef Path)
Definition at line 150 of file FeatureModel.cpp.
References verifyFeatureModelFromBuffer().
verifyFeatureModelFromBuffer()
bool vara::feature::verifyFeatureModelFromBuffer (std::string FileContent)
Definition at line 145 of file FeatureModel.cpp.
References verifyXMLFeatureModelFromBuffer().
Referenced by verifyFeatureModel().
verifyXMLFeatureModelFromBuffer()
bool vara::feature::verifyXMLFeatureModelFromBuffer (std::string FileContent)
Definition at line 140 of file FeatureModel.cpp.
References vara::feature::FeatureModelXmlParser::verifyFeatureModel().
Referenced by verifyFeatureModelFromBuffer().
Variable Documentation
ENCODING
constexpr char vara::feature::ENCODING[] = "UTF-8" static constexpr
Definition at line 23 of file FeatureModelWriter.cpp.
Referenced by vara::feature::FeatureModelXmlWriter::writeFeatureModel().
INDENTATIONSTRING
constexpr xmlChar vara::feature::INDENTATIONSTRING[] = " " static constexpr
Definition at line 22 of file FeatureModelWriter.cpp.