vara-feature: llvm::GraphWriter< vara::feature::FeatureModel * > Struct Reference
llvm::GraphWriter< vara::feature::FeatureModel * > Struct Reference
#include "vara/Feature/FeatureModel.h"
Public Types
using GraphType = typename vara::feature::FeatureModel *
using NodeRef = typename vara::feature::FeatureTreeNode *
using FeatureEdgeSetTy = llvm::SmallSet< std::pair< vara::feature::Feature *, vara::feature::Feature * >, 10 >
Public Member Functions
GraphWriter (raw_ostream &O, const GraphType &G, bool SN)
void writeGraph (const std::string &Title="") const
void writeHeader (const std::string &Title) const
void writeNodes () const
Output tree structure of feature model and additional edges.
void writeFooter () const
void emitCluster (NodeRef Node, const int Indent=0) const
Output feature model (tree) recursively.
void emitNode (NodeRef Node) const
Output Feature node with custom attributes.
void emitEdge (NodeRef SrcNode, NodeRef DestNode, const std::string &Attrs="") const
Static Public Member Functions
static bool visited (std::pair< vara::feature::Feature *, vara::feature::Feature * > Edge, const FeatureEdgeSetTy &Skip)
Checks whether an edge would be a duplicate.
static std::string buildFeatureLabel (vara::feature::Feature *F)
Public Attributes
raw_ostream & O
const GraphType & G
Detailed Description
Definition at line 477 of file FeatureModel.h.
Member Typedef Documentation
FeatureEdgeSetTy
using llvm::GraphWriter< vara::feature::FeatureModel * >::FeatureEdgeSetTy = llvm::SmallSet< std::pair<vara::feature::Feature *, vara::feature::Feature *>, 10>
Definition at line 520 of file FeatureModel.h.
GraphType
using llvm::GraphWriter< vara::feature::FeatureModel * >::GraphType = typename vara::feature::FeatureModel *
Definition at line 478 of file FeatureModel.h.
NodeRef
using llvm::GraphWriter< vara::feature::FeatureModel * >::NodeRef = typename vara::feature::FeatureTreeNode *
Definition at line 483 of file FeatureModel.h.
Constructor & Destructor Documentation
GraphWriter()
llvm::GraphWriter< vara::feature::FeatureModel * >::GraphWriter (raw_ostream & O, const GraphType & G, bool SN) inline
Definition at line 485 of file FeatureModel.h.
Member Function Documentation
buildFeatureLabel()
static std::string llvm::GraphWriter< vara::feature::FeatureModel * >::buildFeatureLabel (vara::feature::Feature * F) inline static
Definition at line 568 of file FeatureModel.h.
References vara::feature::Feature::constraints(), vara::feature::Feature::getLocations(), vara::feature::Feature::getName(), and vara::feature::Feature::hasLocations().
emitCluster()
void llvm::GraphWriter< vara::feature::FeatureModel * >::emitCluster (NodeRef Node, const int Indent = 0) const inline
Output feature model (tree) recursively.
Parameters
[in] Node Root of subtree.
[in] Indent Value to indent statements in dot file.
Definition at line 538 of file FeatureModel.h.
emitEdge()
void llvm::GraphWriter< vara::feature::FeatureModel * >::emitEdge (NodeRef SrcNode, NodeRef DestNode, const std::string & Attrs = "") const inline
Definition at line 623 of file FeatureModel.h.
emitNode()
void llvm::GraphWriter< vara::feature::FeatureModel * >::emitNode (NodeRef Node) const inline
Output Feature node with custom attributes.
Definition at line 595 of file FeatureModel.h.
References vara::feature::Relationship::RK_ALTERNATIVE, and vara::feature::Relationship::RK_OR.
visited()
static bool llvm::GraphWriter< vara::feature::FeatureModel * >::visited (std::pair< vara::feature::Feature *, vara::feature::Feature * > Edge, const FeatureEdgeSetTy & Skip) inline static
Checks whether an edge would be a duplicate.
Parameters
[in] Edge may be already visited.
[in] Skip contains existing edges.
Definition at line 527 of file FeatureModel.h.
writeFooter()
void llvm::GraphWriter< vara::feature::FeatureModel * >::writeFooter () const inline
Definition at line 517 of file FeatureModel.h.
writeGraph()
void llvm::GraphWriter< vara::feature::FeatureModel * >::writeGraph (const std::string & Title = "") const inline
Definition at line 487 of file FeatureModel.h.
writeHeader()
void llvm::GraphWriter< vara::feature::FeatureModel * >::writeHeader (const std::string & Title) const inline
Definition at line 498 of file FeatureModel.h.
writeNodes()
void llvm::GraphWriter< vara::feature::FeatureModel * >::writeNodes () const inline
Output tree structure of feature model and additional edges.
Definition at line 515 of file FeatureModel.h.
Member Data Documentation
G
const GraphType& llvm::GraphWriter< vara::feature::FeatureModel * >::G
Definition at line 481 of file FeatureModel.h.
O
raw_ostream& llvm::GraphWriter< vara::feature::FeatureModel * >::O
Definition at line 480 of file FeatureModel.h.
The documentation for this struct was generated from the following file:
include/vara/Feature/FeatureModel.h