---
0:               '["--cells=52", "--post 0", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--LoopSolver"]'
1:               '["--cells=50", "--post 3", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--LoopSolver"]'
10:              '["--cells=52", "--post 3", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--BiCGSTABSolver"]'
11:              '["--cells=52", "--post 6", "--pre 0", "--Precon", "--SeqSOR", "--Solver", "--BiCGSTABSolver"]'
12:              '["--cells=55", "--post 0", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--BiCGSTABSolver"]'
13:              '["--cells=50", "--post 6", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--BiCGSTABSolver"]'
14:              '["--cells=55", "--post 6", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--BiCGSTABSolver"]'
15:              '["--cells=55", "--post 3", "--pre 0", "--Precon", "--SeqSOR", "--Solver", "--BiCGSTABSolver"]'
16:              '["--cells=52", "--post 0", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--CGSolver"]'
17:              '["--cells=50", "--post 3", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--CGSolver"]'
18:              '["--cells=52", "--post 3", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--CGSolver"]'
19:              '["--cells=52", "--post 6", "--pre 0", "--Precon", "--SeqSOR", "--Solver", "--CGSolver"]'
2:               '["--cells=52", "--post 3", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--LoopSolver"]'
20:              '["--cells=55", "--post 0", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--CGSolver"]'
21:              '["--cells=50", "--post 6", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--CGSolver"]'
22:              '["--cells=55", "--post 6", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--CGSolver"]'
23:              '["--cells=55", "--post 3", "--pre 0", "--Precon", "--SeqSOR", "--Solver", "--CGSolver"]'
24:              '["--cells=52", "--post 0", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--GradientSolver"]'
25:              '["--cells=50", "--post 3", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--GradientSolver"]'
26:              '["--cells=52", "--post 3", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--GradientSolver"]'
27:              '["--cells=52", "--post 6", "--pre 0", "--Precon", "--SeqSOR", "--Solver", "--GradientSolver"]'
28:              '["--cells=55", "--post 0", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--GradientSolver"]'
29:              '["--cells=50", "--post 6", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--GradientSolver"]'
3:               '["--cells=52", "--post 6", "--pre 0", "--Precon", "--SeqSOR", "--Solver", "--LoopSolver"]'
30:              '["--cells=55", "--post 6", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--GradientSolver"]'
31:              '["--cells=55", "--post 3", "--pre 0", "--Precon", "--SeqSOR", "--Solver", "--GradientSolver"]'
32:              '["--cells=52", "--post 0", "--pre 3", "--Precon", "--SeqGS", "--Solver", "--GradientSolver"]'
33:              '["--cells=50", "--post 3", "--pre 3", "--Precon", "--SeqGS", "--Solver", "--GradientSolver"]'
34:              '["--cells=52", "--post 3", "--pre 6", "--Precon", "--SeqGS", "--Solver", "--GradientSolver"]'
35:              '["--cells=52", "--post 6", "--pre 0", "--Precon", "--SeqGS", "--Solver", "--GradientSolver"]'
36:              '["--cells=55", "--post 0", "--pre 6", "--Precon", "--SeqGS", "--Solver", "--GradientSolver"]'
37:              '["--cells=50", "--post 6", "--pre 6", "--Precon", "--SeqGS", "--Solver", "--GradientSolver"]'
38:              '["--cells=55", "--post 6", "--pre 3", "--Precon", "--SeqGS", "--Solver", "--GradientSolver"]'
39:              '["--cells=55", "--post 3", "--pre 0", "--Precon", "--SeqGS", "--Solver", "--GradientSolver"]'
4:               '["--cells=55", "--post 0", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--LoopSolver"]'
5:               '["--cells=50", "--post 6", "--pre 6", "--Precon", "--SeqSOR", "--Solver", "--LoopSolver"]'
6:               '["--cells=55", "--post 6", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--LoopSolver"]'
7:               '["--cells=55", "--post 3", "--pre 0", "--Precon", "--SeqSOR", "--Solver", "--LoopSolver"]'
8:               '["--cells=52", "--post 0", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--BiCGSTABSolver"]'
9:               '["--cells=50", "--post 3", "--pre 3", "--Precon", "--SeqSOR", "--Solver", "--BiCGSTABSolver"]'
...
