name: VaRA Feature Build and Deploy Docs

on:
  push:
    branches: [ vara, vara-dev ]

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install General Dependencies
        shell: bash
        run: |
          sudo apt-key adv --fetch-keys  https://apt.kitware.com/keys/kitware-archive-latest.asc
          sudo apt-add-repository -y 'deb https://apt.kitware.com/ubuntu/ focal main'
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends cmake libstdc++6 libxml2-dev python3-dev graphviz gcc-9 g++-9
          sudo apt-get -y install doxygen

      - name: Install Strategy Dependencies
        shell: bash
        run: |
          sudo apt-key adv --fetch-keys https://apt.llvm.org/llvm-snapshot.gpg.key
          # sudo add-apt-repository -y 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
          sudo add-apt-repository -y 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main'
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends clang-14 llvm-14-dev

      - name: Build docs
        env:
          BUILD_TYPE: Release
          LLVM_VERSION: 14.0
          CXX: clang++-14
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DLLVM_REQUESTED_VERSION=$LLVM_VERSION \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DVARA_FEATURE_BUILD_DOC=True \
            -DVARA_FEATURE_DOXYGEN_SVG=True
          cmake --build . --target build-docs

      - name: Deploy Documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./build/docs/html/
