name: VaRA Feature Library Reviewdog

on:
  pull_request:
    branches: [ vara, vara-dev ]

jobs:
  format:
    runs-on: ubuntu-20.04
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-key adv --fetch-keys https://apt.llvm.org/llvm-snapshot.gpg.key
          sudo add-apt-repository -y 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends clang-format-11

      - name: Fetch Base Branch
        shell: bash
        run: |
          git fetch -n -p --depth=1 --no-recurse-submodules origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

      - name: Run Clang-Format
        shell: bash
        run: |
          FILES=$(git diff --name-only --diff-filter=AM origin/${{ github.base_ref }} HEAD | egrep '\.(c|h|hpp|cpp)$' || true)
          [ -z "$FILES" ] || (clang-format-11 -i $FILES && git diff --diff-filter=M $FILES)

      - name: Add Suggestions
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: clang-format
          filter_mode: diff_context
          level: warning
